### ISSUE TITLE
Maximum field length (63) issue

### ISSUE THREAD

**Issue by SavitaKulkarni** [collectd/collectd#1238] opened 2015-08-24 04:27 UTC
Hi,

We are using GenericJMX plugin to fetch java related statistics from our application.
In our case mbeans are created dynamically considering many configurations.
Most of the times mbeans are created with name > 63 chars. In our case mbean name is the plugin type in collectd.
As in collectd there is a limit on max field length to 63, these names are truncated.
Is it possible to eliminate/increase this max limit for field names in collectd?
Or can we have option to abbreviate field names like we do in /var/log/messages? 

Regards,
Savita

**Comment by druchoo** [comment] 2015-08-28 14:14
The character limitation is global. 63 characters just isn't enough in this day an age and really needs to increased. +1

**Comment by mschenck** [comment] 2015-08-28 19:38
I was able to extend this limit by increasing [DATA_MAX_NAME_LEN](https://github.com/collectd/collectd/blob/master/src/daemon/plugin.h#L42), but after a short period of time (on that new build) metrics would stop being written.  At the time, I was using the [ write_graphite](https://www.collectd.org/documentation/manpages/collectd.conf.5.shtml#plugin_write_graphite), a very limited set of system stats collection(cpu, memory, disk, df, etc), and the [statsd](https://www.collectd.org/wiki/index.php/Plugin:StatsD) plugin.

The only metrics that were exceeding the 63 characters were those written to the statsd plugin, but all metrics would cease to submit.  So, I believe there are additional dependencies on this limit, possibly/hopefully only the write_graphite plugin, but I haven't had time to investigate any further just yet.

**Comment by druchoo** [comment] 2015-08-28 21:09
@mschenck I was tempted to do the same and change DATA_MAX_NAME_LEN, but it seemed too easy and I didn't have time to test. I guess you have confirmed my suspicions. Hopefully it's fairly simple and someone can let us know what exactly needs to be changed.

**Comment by SavitaKulkarni** [comment] 2015-10-07 06:02
Hi,

@mschenck  I did changes of increasing max field length to 264 in my setup with write_graphite plugin no issues observed so far.

Regards,
Savita

**Comment by mschenck** [comment] 2015-12-01 23:15
@SavitaKulkarni have you tried to write something that hits/exceeds this limit?  I believe that might've been happening for me. 


 When I stick with the default `DATA_MAX_NAME_LEN` then the name is just truncated and everything continues on.

My issues started when I increased `DATA_MAX_NAME_LEN` and the name of the metric submitted to the `statsd` plug-in exceeded this value.  We'd have intermittent (eventually total) loss of statsd metrics being submitted, until collectd was restarted.

**Comment by dennisosimon** [comment] 2016-07-08 12:12
+1

**Comment by octo** [comment] 2016-08-03 13:12
Closing this due to 6fd0d2574fc386c2724c8307d33b12529b30048b. If you experience problems with the increased size, please file separate bugs.

**Closed by octo** 2016-08-03 13:12 UTC
