### ISSUE TITLE
ds Cluster.numMon was not properly initialized

### ISSUE THREAD

**Issue by ki4rbc** [collectd/collectd#3146] opened 2019-05-10 17:18 UTC
## Software Versions

*   Version of collectd:  5.5.1

*   Version of ceph: 13.2.5 (mimic)

*   Operating system / distribution: Ubuntu / 16.04.6 LTS (xenial)

*   Kernel version (if applicable):  4.4.0-145-generic

## Expected behavior

Error not present in log

## Actual behavior

The following error present in log:

`May 10 16:55:18 pod4compute2-admin collectd[7041]: ceph plugin: ds Cluster.numMon was not properly initialized.`
`May 10 16:55:18 pod4compute2-admin collectd[7041]: ceph plugin: JSON handler failed with status -1.`
`May 10 16:55:18 pod4compute2-admin collectd[7041]: ceph plugin: cconn_handle_event(name=mon.a,i=0,st=4): error 1`

## Relevant ceph perf dump
`    "cluster": {`
`        "num_mon": 3,`
`        "num_mon_quorum": 3,`
`        "num_osd": 9,`
`        "num_osd_up": 9,`
`        "num_osd_in": 9,`
`        "osd_epoch": 64,`
`        "osd_bytes": 4558436831232,`
`        "osd_bytes_used": 1071875399680,`
`        "osd_bytes_avail": 3486561431552,`
`        "num_pool": 5,`
`        "num_pg": 640,`
`        "num_pg_active_clean": 640,`
`        "num_pg_active": 640,`
`        "num_pg_peering": 0,`
`        "num_object": 555050,`
`        "num_object_degraded": 0,`
`        "num_object_misplaced": 0,`
`        "num_object_unfound": 0,`
`        "num_bytes": 373144943373`
`    },`

 
## Steps to reproduce

*   create a ceph cluster
    *   install ubuntu (xenial) 
    *   install cepf (mimic)
        *  create cepf monitor and storage (osd)
    *   install collectd 5.5.1
        *  config collectd plugin ceph
    *   tail syslog

**Comment by rubenk** [comment] 2019-05-13 11:37
Collectd 5.5.1 is not supported anymore. Can you reproduce this with the latest Collectd version?

**Comment by ki4rbc** [comment] 2019-05-13 14:32
I tried that already;5.8.0.145.gca1cb27. While this error went away, issues mentioned in issues #2343 and #2654 presented themselves. What latest version of collectd still supports ceph mimic?

**Here are the details**
**Errors in log**
**-------------**
/var/log/collectd/log

`[2019-05-10 15:23:36] [error] ceph plugin: ds FinisherMonFinisher.completeLatency.avgtime was not properly initialized.`
`[2019-05-10 15:23:36] [error] ceph plugin: JSON handler failed with status -1.`
`[2019-05-10 15:23:36] [warning] ceph plugin: cconn_handle_event(name=mon.a,i=4,st=4): error 1`
`[2019-05-10 15:23:36] [error] ceph plugin: ds Client.reply.avgtime was not properly initialized.`
`[2019-05-10 15:23:36] [error] ceph plugin: JSON handler failed with status -1.`
`[2019-05-10 15:23:36] [warning] ceph plugin: cconn_handle_event(name=mgr.a,i=3,st=4): error 1`
`[2019-05-10 15:23:36] [error] ceph plugin: ds Filestore.journalLatency.avgtime was not properly initialized.`
`[2019-05-10 15:23:36] [error] ceph plugin: JSON handler failed with status -1.`
`[2019-05-10 15:23:36] [warning] ceph plugin: cconn_handle_event(name=osd.1,i=0,st=4): error 1`
`[2019-05-10 15:23:36] [error] ceph plugin: ds Filestore.journalLatency.avgtime was not properly initialized.`
`[2019-05-10 15:23:36] [error] ceph plugin: JSON handler failed with status -1.`
`[2019-05-10 15:23:36] [warning] ceph plugin: cconn_handle_event(name=osd.5,i=1,st=4): error 1`
`[2019-05-10 15:23:36] [error] ceph plugin: ds Filestore.journalLatency.avgtime was not properly initialized.`
`[2019-05-10 15:23:36] [error] ceph plugin: JSON handler failed with status -1.`
`[2019-05-10 15:23:36] [warning] ceph plugin: cconn_handle_event(name=osd.8,i=2,st=4): error 1`

**Issues with like errors reported**
**--------------------------------**
https://github.com/collectd/collectd/issues/2343
https://github.com/collectd/collectd/issues/2654

**Software versions**
**-----------------**
Ubuntu    16.04.6 LTS (xenial)
collectd  5.8.0.145.gca1cb27
ceph      13.2.5-1xenial (mimic)

**Snippet from mon.a perf dump**
**-----------------------------**
`    "finisher-mon_finisher": {'
`        "queue_len": 0,'
`        "complete_latency": {'
`            "avgcount": 0,'
`            "sum": 0.000000000,'
`            "avgtime": 0.000000000'
`        }'
`    },'

**Snippet from mgr.a perf dump
**----------------------------
`    "client": {'
`        "reply": {'
`            "avgcount": 0,'
`            "sum": 0.000000000,'
`            "avgtime": 0.000000000'
`        },'
`        "lat": {'
`            "avgcount": 0,'
`            "sum": 0.000000000,'
`            "avgtime": 0.000000000'
`        },'
`        "wrlat": {'
`            "avgcount": 0,'
`            "sum": 0.000000000,'
`            "avgtime": 0.000000000'
`        }'
`    },'

**Snippet from osd.1 perf dump**
**----------------------------**
`    "filestore": {'
`        "journal_queue_ops": 0,'
`        "journal_queue_bytes": 0,'
`        "journal_ops": 68,'
`        "journal_bytes": 888832,'
`        "journal_latency": {'
`            "avgcount": 2529342,'
`            "sum": 4377.538938063,'
`            "avgtime": 0.001730702'
`        },'
`        "journal_wr": 2500700,'
`        "journal_wr_bytes": {'
`            "avgcount": 2500700,'
`            "sum": 85891379200'
`        },'
`        "journal_full": 0,'
`        "committing": 0,'
`        "commitcycle": 10796,'
`        "commitcycle_interval": {'
`            "avgcount": 10796,'
`            "sum": 54317.141256557,'
`            "avgtime": 5.031228349'
`        },'
`        "commitcycle_latency": {'
`            "avgcount": 10796,'
`            "sum": 336.159061778,'
`            "avgtime": 0.031137371'
`        },'
`        "op_queue_max_ops": 50,'
`        "op_queue_ops": 0,'
`        "ops": 2529342,'
`        "op_queue_max_bytes": 104857600,'
`        "op_queue_bytes": 0,'
`        "bytes": 78670695723,'
`        "apply_latency": {'
`            "avgcount": 2529342,'
`            "sum": 5181.925183872,'
`            "avgtime": 0.002048724'
`        },'
`        "queue_transaction_latency_avg": {'
`            "avgcount": 2529342,'
`            "sum": 126.415533460,'
`            "avgtime": 0.000049979'
`        },'
`        "sync_pause_max_latency": 10.000214368'
`    },'

**Comment by rubenk** [comment] 2019-05-14 10:00
In that case I'll close this issue since it's a duplicate.

It's a shame, but there's nobody actively keeping the plugin up to date with newer Ceph versions. Any help and patches are greatly appreciated.

**Closed by rubenk** 2019-05-14 10:00 UTC

**Comment by ki4rbc** [comment] 2019-05-14 14:56
So I got the `ds Filestore.journalLatency.avgtime was not properly initialized` errors when trying collectd version 5.6.3.2.gcb966fc. So it looks like my only choices are to upgrade ceph, a heavy lift, or patch 5.5.3.1.g4f9adee. 

On your comment: "Collectd 5.5.1 is not supported anymore," This is the version published in "Ubuntu 16.04.6 LTS" repo:
`# apt policy collectd`
`collectd:`
`  Installed: (none)`
`  Candidate: 5.5.1-1build2`
`  Version table:`
`     5.5.1-1build2 500`
`        500 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages`
`# `

I look at what is needed to read ceph 13.2.5 perf dump json files and what collectd 5.8 is expecting. Do you think it would make sense to allow a collectd config option to select which ceph version it needs to parse?

**Comment by rubenk** [comment] 2019-05-14 15:37
We (the upstream Collectd project, where you've reported this issue) do not support 5.5.1 anymore.
We have no say over what versions Ubuntu ships and support.

I think Collectd should be able to handle Ceph versions transparently if possible.
