### ISSUE TITLE
[error] turbostat plugin: Unable to save the CPU affinity

### ISSUE THREAD

**Issue by jessetan** [collectd/collectd#1593] opened 2016-03-03 15:10 UTC
I'm using collectd-turbostat on multiple servers to get cpu temperature and frequency, but there is one where the error `[error] turbostat plugin: Unable to save the CPU affinity` keeps appearing in the collectd.log and nothing is measured.

Any ideas on how I can troubleshoot this? This is a non-virtual machine, running collectd 5.5.0 on Centos 6.5

**Comment by rpv-tomsk** [comment] 2016-03-09 12:47
Could you please build patched version of plugin with more detailed error message?

Patch: https://github.com/rpv-tomsk/collectd/commit/a83be57f260df1f948650f36143904fbaa99da35

**Comment by jessetan** [comment] 2016-03-09 14:40
`[2016-03-09 14:14:12] [error] turbostat plugin: Unable to save the CPU affinity: Invalid argument`

If I modify your patch to print the arguments:
```
ERROR("turbostat plugin: Unable to save the CPU affinity (cpu_saved_affinity_setsize %zu, CPU_COUNT(cpu_saved_affinity_set) %i): %s",
                                cpu_saved_affinity_setsize,
                                CPU_COUNT(cpu_saved_affinity_set),
                                sstrerror (errno, errbuf, sizeof (errbuf)));
```

The output becomes:
`[error] turbostat plugin: Unable to save the CPU affinity (cpu_saved_affinity_setsize 16, CPU_COUNT(cpu_saved_affinity_set) ##): Invalid argument` with varying values for ## (I've seen anything from 56 to 74, note that `nproc` returns 72)

**Comment by rpv-tomsk** [comment] 2016-03-09 16:42
Thanks for extended info.

For dynamically allocated sets, (cpu_saved_affinity_set is dynamically allocated) CPU_COUNT_S() should be used instead of CPU_COUNT().  Please see http://linux.die.net/man/3/cpu_set for this.

In your case: CPU_COUNT_S(cpu_saved_affinity_setsize, cpu_saved_affinity_set).


If you want to dig, 'turbostat' tool source is at https://github.com/torvalds/linux/blob/0b2bb6925eb602eae993a4b5c282a8c18ad1c949/tools/power/x86/turbostat/turbostat.c (or newer revision).

For your problem, the following can be done:

1) Try to replace dynamic allocation of cpu_saved_affinity_set via static declaration.  Not sure how this can helps, but..
Don't forget about CPU_ZERO() if you would try.

2) Try to remove sched_getaffinity() and cpu_saved_affinity_set variable at all, replace it by sched_setaffinity(0, cpu_present_setsize, cpu_present_set) at end of turbostat_read(); like it was done in https://github.com/torvalds/linux/blob/0b2bb6925eb602eae993a4b5c282a8c18ad1c949/tools/power/x86/turbostat/turbostat.c#L2762 . This set affinity for collectd read thread(s) to all CPUs, present in system, and it is less correct than current solution but it can work for you.

Could you please show 'cat /proc/stat' also?

**Comment by rpv-tomsk** [comment] 2016-03-09 16:48
Did you try to run 'turbostat' tool on that server ?

**Comment by rpv-tomsk** [comment] 2016-03-09 16:59
Also: https://sourceware.org/bugzilla/show_bug.cgi?id=15630

**Comment by jessetan** [comment] 2016-03-10 10:03
Thanks for your detailed response.
- Running `turbostat` generates statistics as expected
- Implementing your suggestion 2 (Removing sched_getaffinity() and cpu_saved_affinity_set and setting `sched_setaffinity(0, cpu_present_setsize, cpu_present_set)` at end of `turbostat_read`) stops the error from occuring.
- According to http://linux.die.net/man/2/sched_getaffinity, a return value of EINVAL may indicate "cpusetsize is smaller than the size of the affinity mask used by the kernel.", so I tried changing the value passed to `CPU_ALLOC_SIZE` in https://github.com/rpv-tomsk/collectd/blob/a83be57f260df1f948650f36143904fbaa99da35/src/turbostat.c#L1141 to 129 or higher. This returns 24 bytes for the cpuset size, rather than 16 and also stops the error from occurring. Ofcourse there are not 129 CPUs, but 72 (2 CPUs * 18 cores * 2 for hyperthreading)

- Output of `cat /proc/stat`:
```
cpu  17486383 2223 1850753 226864809 692 28 190153 0 0
cpu0 345279 28 55094 2991116 194 12 25990 0 0
cpu1 313142 59 49065 3055464 194 0 4025 0 0
cpu2 331089 72 54548 3008652 6 15 28438 0 0
cpu3 295823 72 45046 3075817 10 0 4125 0 0
cpu4 338838 26 42544 3015384 5 0 4234 0 0
cpu5 288551 21 40265 3087808 7 0 3669 0 0
cpu6 336495 3 41652 3036767 3 0 3922 0 0
cpu7 274362 5 33478 3107464 4 0 3268 0 0
cpu8 324487 2 39484 3048627 4 0 3634 0 0
cpu9 273158 3 30082 3115063 6 0 2849 0 0
cpu10 323812 4 37154 3059722 1 0 3484 0 0
cpu11 269246 8 27599 3120767 2 0 2651 0 0
cpu12 331871 4 41840 3049034 1 0 3281 0 0
cpu13 267886 4 25778 3124996 2 0 2382 0 0
cpu14 322023 2 34934 3062464 1 0 3029 0 0
cpu15 252454 3 24435 3142263 2 0 2123 0 0
cpu16 313512 2 33860 3076289 1 0 2891 0 0
cpu17 245196 3 24447 3151466 3 0 1926 0 0
cpu18 311531 1 32085 3076214 1 0 2775 0 0
cpu19 248067 0 20897 3155235 2 0 1829 0 0
cpu20 320456 10 34164 3070299 1 0 2717 0 0
cpu21 240538 2 21379 3158220 2 0 1744 0 0
cpu22 311631 5 35189 3074624 1 0 2680 0 0
cpu23 236437 5 24164 3163787 1 0 1638 0 0
cpu24 313928 3 31266 3079720 5 0 2609 0 0
cpu25 231668 6 19379 3175172 4 0 1573 0 0
cpu26 298183 1 29932 3091265 1 0 2468 0 0
cpu27 230275 2 19312 3176602 1 0 1512 0 0
cpu28 305746 3 32128 3083838 0 0 2361 0 0
cpu29 229302 4 18538 3179923 1 0 1410 0 0
cpu30 305390 8 30574 3089842 8 0 2374 0 0
cpu31 224259 5 18185 3177522 1 0 1371 0 0
cpu32 301932 3 29648 3087172 1 0 2340 0 0
cpu33 222389 1 17236 3184616 2 0 1358 0 0
cpu34 286412 1 27461 3107184 0 0 2225 0 0
cpu35 225956 2 22681 3182132 1 0 1329 0 0
cpu36 244433 2 33718 3133342 7 0 2140 0 0
cpu37 192764 1 22016 3197991 38 0 1371 0 0
cpu38 236073 383 33171 3148274 55 0 2045 0 0
cpu39 180374 455 27293 3212558 37 0 1428 0 0
cpu40 229328 110 27716 3152856 5 0 1872 0 0
cpu41 177234 200 22384 3216161 5 0 1298 0 0
cpu42 223359 42 24731 3173118 1 0 1803 0 0
cpu43 183404 70 20196 3219904 3 0 1251 0 0
cpu44 227940 36 24343 3165881 1 0 1758 0 0
cpu45 175837 444 19577 3228844 1 0 1138 0 0
cpu46 241681 3 24700 3153608 0 0 1734 0 0
cpu47 178890 16 18881 3220286 0 0 1128 0 0
cpu48 228365 10 22463 3170181 0 0 1658 0 0
cpu49 175432 6 14991 3229247 1 0 1077 0 0
cpu50 228527 0 21983 3169826 0 0 1622 0 0
cpu51 176374 2 14620 3220814 1 0 1020 0 0
cpu52 227869 1 23034 3164452 0 0 1556 0 0
cpu53 177399 2 15882 3236983 1 0 995 0 0
cpu54 226135 3 19655 3180114 1 0 1519 0 0
cpu55 170208 2 12590 3238747 1 0 947 0 0
cpu56 213044 0 21199 3187403 0 0 1412 0 0
cpu57 169616 1 13001 3240553 1 0 925 0 0
cpu58 226523 0 21120 3175491 0 0 1480 0 0
cpu59 169834 4 12964 3232907 1 0 944 0 0
cpu60 215197 2 18089 3189032 0 0 1435 0 0
cpu61 170341 3 12258 3239343 1 0 901 0 0
cpu62 223835 0 20853 3175745 0 0 1466 0 0
cpu63 167276 0 12758 3241800 1 0 897 0 0
cpu64 220225 0 18762 3182507 0 0 1414 0 0
cpu65 165875 0 13418 3244635 2 0 865 0 0
cpu66 214637 5 18620 3187052 0 0 1379 0 0
cpu67 167112 0 11431 3243788 1 0 879 0 0
cpu68 220243 0 19234 3182788 10 0 1434 0 0
cpu69 166159 0 11700 3237656 1 0 849 0 0
cpu70 218691 0 21437 3182652 0 0 1410 0 0
cpu71 164795 0 14400 3245706 1 0 831 0 0
intr 1472565174 239 0 0 0 85 0 0 0 1 3 248 0 0 0 0 0 0 0 111 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 114 0 0 0 0 0 0 0 0 0 0 0 0 110511 211213 3078 9253 3783 8927 1692 4467 1148 4143 773 3105 835 2842 724 3116 827 1821 426 2425 674 2269 636 1763 636 1841 630 1890 586 1894 582 1505 494 1495 567 1289 13693 42001 1766 2603 671 2388 414 795 388 974 286 899 246 951 653 921 372 1099 487 882 312 946 322 854 166 781 261 999 300 1217 611 1020 298 960 241 1109 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 10958497 1814516 7864262 1782891 3095136 1593269 2731265 1501299 2383072 911052 1498338 689381 1411303 602559 1333779 555654 1275497 450783 1075661 445660 1163602 446626 1065367 453306 873579 402773 1071383 484641 847308 440173 965402 461783 1001484 415325 838243 537650 3700356 988758 3204922 827314 1451518 636301 1332900 646241 1160920 505889 1121641 491256 974910 437370 964522 507816 893646 477855 795358 374771 803892 482446 811621 601309 575027 464895 1012783 82 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
ctxt 2727003925
btime 1457568775
processes 1950685
procs_running 1
procs_blocked 0
softirq 922142548 0 265255693 7737 333159536 334624 0 39120 52028219 296020 271021599
```

**Comment by rpv-tomsk** [comment] 2016-03-10 12:31
Hi!

> Running turbostat generates statistics as expected

Sure, it does not use sched_getaffinity().

> ... a return value of EINVAL may indicate "cpusetsize is smaller than the size of the affinity mask used by the kernel."

... and this is libc and kernel api problem, not collectd. And I don't know how to solve this without hacks or without replacing dynamic allocation via static declaration. Static declaration will limit number of supported CPU threads to 1024, which is a kind of regression :-) :-)

Static declaration has sizeof(cpu_set_t) == 128, this is much bigger than 16, got from dynamic allocation, so it would work.

Could you please show some lines from  'dmesg |grep -i CPU' at your server?
I am interested in lines like these:

[    0.000000] SMP: Allowing 4 CPUs, 2 hotplug CPUs
[    0.000000] setup_percpu: NR_CPUS:32 nr_cpumask_bits:32 nr_cpu_ids:4 nr_node_ids:1
[    0.000000] PERCPU: Embedded 14 pages/cpu @dcbad000 s33280 r0 d24064 u57344
[    0.000000] pcpu-alloc: s33280 r0 d24064 u57344 alloc=14*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3

**Comment by jessetan** [comment] 2016-03-10 13:08
```
SMP: Allowing 144 CPUs, 72 hotplug CPUs
NR_CPUS:4096 nr_cpumask_bits:144 nr_cpu_ids:144 nr_node_ids:2
PERCPU: Embedded 31 pages/cpu @ffff880061600000 s94872 r8192 d23912 u131072
pcpu-alloc: s94872 r8192 d23912 u131072 alloc=1*2097152
pcpu-alloc: [0] 000 002 004 006 008 010 012 014 016 018 020 022 024 026 028 030
pcpu-alloc: [0] 032 034 036 038 040 042 044 046 048 050 052 054 056 058 060 062
pcpu-alloc: [0] 064 066 068 070 072 074 076 078 080 082 084 086 088 090 092 094
pcpu-alloc: [0] 096 098 100 102 104 106 108 110 112 114 116 118 120 122 124 126
pcpu-alloc: [0] 128 130 132 134 136 138 140 142 --- --- --- --- --- --- --- ---
pcpu-alloc: [1] 001 003 005 007 009 011 013 015 017 019 021 023 025 027 029 031
pcpu-alloc: [1] 033 035 037 039 041 043 045 047 049 051 053 055 057 059 061 063
pcpu-alloc: [1] 065 067 069 071 073 075 077 079 081 083 085 087 089 091 093 095
pcpu-alloc: [1] 097 099 101 103 105 107 109 111 113 115 117 119 121 123 125 127
pcpu-alloc: [1] 129 131 133 135 137 139 141 143 --- --- --- --- --- --- --- ---
```

**Comment by rpv-tomsk** [comment] 2016-03-11 06:54
You can try to set kernel parameter 'possible_cpus=128' to solve your issue without patching collectd.

**Comment by jessetan** [comment] 2016-03-14 10:05
Appending `possible_cpus=128` to the end of the `kernel` line in `/etc/grub.conf` provided a usable workaround for now, but of course this will not work for anyone with > 128 cpus.
Hopefully this can be resolved between glibc and kernel (perhaps https://sourceware.org/bugzilla/show_bug.cgi?id=19143 ?)
Thanks for your help @rpv-tomsk.

**Comment by rpv-tomsk** [comment] 2016-03-14 12:12
Nope, this will work. 
If anyone has more than 128 CPUs, then the user-side SIZE will be greater too.
So, you should put the next 'size', ie 160 into 'possible_cpus'.
The idea is to reduce (maybe down to zero) 'hotplug' CPU quantity (provided by BIOS?), so  SIZE(online_CPUs) (at user-side)  will be equal to SIZE(possible_cpus) (at kernel-side).

**Comment by jessetan** [comment] 2016-03-16 13:56
I meant that this is not a universal fix for every situation, unfortunately we are dependent on libc and kernel having same semantics. But this workaround can be used, just not easily automated.

**Comment by Feandil** [comment] 2016-05-17 14:03
Another solution could be to simplify the behavior of the plugin. Saving and restoring the cpu_affinity might not be worth it: is it expected to be non default?

For example, we could:
- If sched_getaffinity fails, set a flag to remember it and use cpu_present_set instead of cpu_saved_affinity_set to restore the affinity
- Add a configuration option (not sure what default would make more sense) to replace the save/restore with a simple restoration of cpu_present_set
- Same as the solutions before, but replace cpu_present_set with a set of site max_cpu_id all filed with 1s

**Comment by pllopis** [comment] 2018-01-22 16:07
Even though this issue is old, the underlying issues persist on modern systems. The above pull request is an attempt to solve the issue taking into account the comments mentioned in this thread. Would love any feedback in case there's any chance a fix for this can be merged, since otherwise this plugin is probably broken on many modern systems with CentOS.

**Comment by pllopis** [comment] 2018-03-13 13:23
I just updated the code in the PR above with a more elegant approach (IMHO): a new parameter to configure the policy to be used for restoring the cpu affinity. By default it will behave as it has until now, but there is also the option to restore affinity to all cpus (and skip the sched_getaffinity call).

**Closed** 2020-03-18 10:28 UTC
Labels: Pending feedback
