### ISSUE TITLE
Plugin write_graphite when multiple nodes (destinations) if one fails then all stop

### ISSUE THREAD

**Issue by nb71** [collectd/collectd#2396] opened 2017-08-11 19:11 UTC
*   Version of collectd: 5.7.1
*   Operating system / distribution: centos 7

## Expected behavior
Plugin write_graphite should continue working when many nodes configured and one of them is unreachable.

## Actual behavior
when a configured node is unreachable (network/firewall/graphite down) the other one
is't receiving any data

## Steps to reproduce
Configure 2 nodes to Plugin write_graphite in collectd.conf: 
```
<Plugin write_graphite>
  <Node "one">
    Host "1.2.3.4"
    Port "2003"
    Prefix "collectd."
#    Postfix "."
    StoreRates true
    AlwaysAppendDS false
    SeparateInstances true
    EscapeCharacter "_"
  </Node>
  <Node "two">
    Host "5.6.7.8"
    Port "2003"
    Prefix "collectd."
#    Postfix "."
    StoreRates true
    AlwaysAppendDS false
    SeparateInstances true
    EscapeCharacter "_"
  </Node>
</plugin>
```
When 1.2.3.4 and 5.6.7.8 are reachable and have a graphite server running everything is ok.

Change 1.2.3.4 to a non reachable ip or shutdown graphite server,
restart collectd.
the second server will not receive any updates.

Restore server OR remove it from the config and it will be OK again.
Thanks!

**Comment by rubenk** [comment] 2017-08-12 12:04
This is a duplicate of #1140

**Closed by rubenk** 2017-08-12 12:04 UTC
Labels: Pending feedback

**Comment by Jingwei-Tang91** [comment] 2018-09-10 02:43
In collectd-5.8, I also see this problem.  Are there any else solution to fix it? Thanks
