### ISSUE TITLE
network plugin: Initialization of libgcrypt fails on FreeBSD

### ISSUE THREAD

**Issue by wtps0n** [collectd/collectd#1870] opened 2016-08-09 08:31 UTC
envinronment:
FreeBSD 10.3-STABLE #3 r301168: Thu Jun  2 00:06:02 CEST 2016 amd64
collectd 5.5.2 (latest pkg upgrade from FreeBSD ports)
libgcrypt: libgcrypt-1.7.2 (build from ports).
collectd.conf:
<Plugin network>
        <Listen "10.2.2.1" "25826">
                SecurityLevel Sign
                AuthFile "/usr/local/etc/collectd/passwd"
                Interface "bge0"
        </Listen>
        TimeToLive 128
        MaxPacketSize 8192
        ReportStats true
        Forward false
        ##CacheFlush 180
</Plugin>

kernel message:
Aug  9 08:59:25 fw collectd[18731]: network plugin: gcry_control (GCRYCTL_SET_THREAD_CBS) failed: General error
Aug  9 08:59:25 fw collectdmon[18718]: Warning: collectd was terminated by signal 6 (core dumped)
Aug  9 08:59:25 fw kernel: pid 18731 (collectd), uid 0: exited on signal 6 (core dumped)

Also another users (debian) report similiar issues:
http://osdir.com/ml/general/2016-07/msg40034.html

 I've checked source code. As I can see there is condition checking if libgcrypt version is LESS THAN number. But as I can see FreeBSD supports latest version of libgcrypt.

I hope this will help to find a bug.

**Comment by rubenk** [comment] 2016-08-09 09:42
@tokkee does this look like the same issue you fixed on Debian?

**Comment by octo** [comment] 2016-08-09 15:18
`GCRYCTL_SET_THREAD_CBS` used to be necessary in old versions of *libgcrypt* and was eventually obsoleted. The macro is still there for backwards compatibility, but should be a *nop*.

We try to detect the *libgcrypt* version and only call this when needed. Since this appears to be called, it must be a pre-1.6 version of the library.

I think you're referring to [Debian bug #833013](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=833013). Sebastian tracked this down to 0ec776abf45ef3989f38d966e74b588f9ef15ebe which first was included in the 5.1.3 and 5.2.2 releases.

@wtps0n Sebastian mentions an error message that is printed by *libgcrypt* when initialization fails due to the wrong call order. Could you please run collectd in the foreground (the `-f` option) and check for such a message?

**Comment by rubenk** [comment] 2016-08-09 15:24
The error message is wrong, this is fixed by 262915c
The abort() is turned into an error by a3000c

I can now reproduce this on FreeBSD, and the actual error is 
```
[2016-08-09 17:17:17] network plugin: gcry_control (GCRYCTL_INIT_SECMEM) failed: General error
[2016-08-09 17:17:17] network plugin: Cannot configure client socket with security: Failed to initialize crypto library.
[2016-08-09 17:17:17] network plugin: network_config_add_server: sockent_init_crypto() failed.
```

I tried to debug libgcrypt:
```
secmem_init (n=32768) at secmem.c:522
522		  lock_pool (pool, n);
(gdb) s
lock_pool (p=0x80069c000, n=32768) at secmem.c:287
287	  uid = getuid ();
(gdb) n
294	  if (uid)
(gdb) 
296	      errno = EPERM;
(gdb) 
297	      err = errno;
(gdb) 
298	    }
(gdb) 
```

So it seems to be caused my me running collectd as non-root.

**Comment by rubenk** [comment] 2016-08-09 15:30
Same error when running this as root, but a different cause:
```
Breakpoint 1, lock_pool (p=0x80069c000, n=32768) at secmem.c:287
287	  uid = getuid ();
(gdb) n
294	  if (uid)
(gdb) 
301	      err = no_mlock? 0 : mlock (p, n);
(gdb) n
302	      if (err && errno)
(gdb) p err
$1 = -1
(gdb) p errno
$2 = 2
(gdb) p p
$3 = (void *) 0x80069c000
(gdb) p n
$4 = 32768
```

**Comment by rubenk** [comment] 2016-08-09 17:58
errno 2 is ENOENT, which doesn't make sense for mlock().

In any case, libgcrypt can't lock 32KB of memory. I'm not sure Collectd can do more about it than report an error.

**Comment by wtps0n** [comment] 2016-08-10 06:42
Do I have to start collectd with -f flag? I can confirm, that collectd is running with root (only exec plugin is executed with unprivileged user).

**Comment by octo** [comment] 2016-08-10 07:15
@wtps0n yes, you need to use `-f`: the error message I'd like you to look for is written by the library itself. It's likely that it is written to `STDOUT` or `STDERR`, both of which are opened to `/dev/null` when forked to the background. @tokkee also mentions syslog, so maybe check that, too.

**Comment by wtps0n** [comment] 2016-08-10 07:30
OK.. running collectd -f prints only "core dump". More messages are from syslog (messages). I put them in my first post. I can write more from gdb, but I'll need some help :-)

**Comment by tokkee** [comment] 2016-08-10 22:22
Which version of libgcrypt is this? In 1.5 and 1.7, the code belonging to this backtrace says:

    #ifdef HAVE_BROKEN_MLOCK
      /* Under HP/UX mlock segfaults if called by non-root.  Note, we have
         noch checked whether mlock does really work under AIX where we
         also detected a broken nlock.  Note further, that using plock ()
         is not a good idea under AIX. */
      if (uid)
      …

So, that explains the behavior as non-root but leaves the question how mlock() is broken on FreeBSD.

Anyway, I don't think this is related to the other issues we had seen so far.

**Comment by rubenk** [comment] 2016-08-11 07:47
@tokkee 1.7, and indeed, it matches the HAVE_BROKEN_MLOCK code.

**Comment by rubenk** [comment] 2016-08-11 09:02
Perhaps mlock is not really broken, but libgcrypt's configure check decides it is? I hacked their check to return the mlock errno, and it returns EAGAIN. If mlock returns any error they decide it is broken.

I see the issue now. Here's the code that gets run un-ifdeffed:
```
lock_pool (void *p, size_t n)
{ 
  /* Under HP/UX mlock segfaults if called by non-root.  Note, we have
     noch checked whether mlock does really work under AIX where we
     also detected a broken nlock.  Note further, that using plock ()
     is not a good idea under AIX. */
  if (uid)
    { 
      errno = EPERM;
      err = errno;
    }
  else
    { 
      err = no_mlock? 0 : mlock (p, n);
      if (err && errno)
        err = errno;
    }
  
  /* Test whether we are running setuid(0).  */
  if (uid && ! geteuid ())
    { 
      /* Yes, we are.  */
      if (!no_priv_drop)
        { 
          /* Check that we really dropped the privs.
           * Note: setuid(0) should always fail */ 
          if (setuid (uid) || getuid () != geteuid () || !setuid (0))
            log_fatal ("failed to reset uid: %s\n", strerror (errno));
        }
    }
  
  if (err)
    { 
      if (errno != EPERM
#ifdef EAGAIN   /* OpenBSD returns this. */
          && errno != EAGAIN
#endif
#ifdef ENOSYS   /* Some SCOs return this (function not implemented). */
          && errno != ENOSYS
#endif
#ifdef ENOMEM  /* Linux might return this. */
            && errno != ENOMEM
#endif    
          )
        log_error ("can't lock memory: %s\n", strerror (err));
      show_warning = 1;
      not_locked = 1;
    }
  
  (void)p;
  (void)n;
  if (!no_mlock)
    log_info ("Please note that you don't have secure memory on this system\n");
}
```

The call to geteuid() overwrites errno and sets it to 2. That explains the ENOENT I saw earlier.
The real errno is 35, EAGAIN, but this never matches.

The only effect of this is that it does'n log an error.
In any case, this is still set:
```
 show_warning = 1;
      not_locked = 1
```
and libgcrypt returns a generic error.

Apart from this bug, that still leaves us with the question why mlock returns EAGAIN.

**Comment by rubenk** [comment] 2016-08-11 10:45
@wtps0n are you running ZFS on your system by any chance? I think you might be running into the issue described at http://ximalas.info/2012/04/10/not-enough-room-for-wired-pages/

mlock bumps into the wired pages limit. I can reproduce this as follows:
```
cat /home/ruben/test2.c 
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <sys/mman.h>

int main(void)
{

  size_t pool_size = 32768;
  void *pool = mmap (0, pool_size, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);

  if (pool == (void *) -1) {
      perror("mmap");
      return 1;
  }

  int err = mlock(pool, pool_size);
  if (err) {
      fprintf(stderr, "mlock: %s(%d)\n", strerror(errno), errno);
      return 1;
  }

  return 0;
}

[root@fikkie ~]# sysctl vm.max_wired
vm.max_wired: 651444
[root@fikkie ~]# /home/ruben/test2 
mlock: Resource temporarily unavailable(35)
[root@fikkie ~]# sysctl vm.max_wired=1835008
vm.max_wired: 651444 -> 1835008
[root@fikkie ~]# /home/ruben/test2 
```

**Comment by wtps0n** [comment] 2016-08-11 12:14
Yes, I'm running ZFS on my FreeBSD box. I read ximalas article. I will try to set sysctl vm.max_wired=1835008 and check again. Maybe that's the clue.

**Comment by rubenk** [comment] 2016-08-11 12:16
I think it is, I can't reproduce this on a box without ZFS, but looking forward to your confirmation.

In any case, I advise you to apply 262915c and a3000cb to the FreeBSD port, that will at least stop Collectd from aborting and give the proper error message.

**Comment by wtps0n** [comment] 2016-08-11 12:18
OK. I've set sysctl to new value. Upgraded collectd and it is running. I will have to wait a liitle time to be sure that collectd "clients" (other servers) sending data and it's collected correctly.

**Comment by wtps0n** [comment] 2016-08-11 12:36
OK. It works correctly. I will add suggested patches to FreeBSD port and check again.

**Comment by brd** [comment] 2016-08-11 12:41
@rubenk Awesome analysis!!

@wtps0n if that works, I will update the port.

**Comment by rubenk** [comment] 2016-08-11 12:43
Thanks @brd! Are you willing to follow up on the mlock / vm.max_wired issue on the FreeBSD side? I couldn't find any open bug reports, but this seems to be a known issue for a long time.

**Comment by arader** [comment] 2016-08-21 15:10
I updated to 5.5.2 on my FreeBSD box and after upping the max wired size (to 4194304 in my case) worked.

If I'm reading the patches above, if they were applied, while in this state you'd no longer see collectd crash, but the network plugin wouldn't load, correct? I'd argue that that's just as bad, hosts that rely on the network plugin aren't going to send any data either way.

So is an actual fix possible? Is this gcrypt requirement new? I assume this likely repros more often on a FreeBSD machine that's been up for a while (lots of wired pages already) versus one that's just rebooted.

**Comment by wtps0n** [comment] 2016-08-28 20:24
Hello,

Well I've tested (installed) new version of collectd on servers with uptime more than one month. These servers are a little different: one f them are standalone (they don't use network plugin). Some of them are using this plugin.

On "networked" servers I've set sysctl wired pages and it seems that there are no problems with network plugin. ( I'm using configutaion with packet signing).

After reading this discussion also I'm concluding that's the problem with gcrypt, not with network plugin. To be sure you have to test network configuration neither with signing nor crypting - libgcrypt will not be used. And then we will be sure.

Also remember that you can send collected packets without any signing/crypting. But this is a secure best parctice - recommendation event inside closed environments. That's why libgcrypt is used.

I hope that's clear :-)

**Comment by arader** [comment] 2016-08-28 20:43
I'm not using encryption at all and I hit this issue. If gcrypt really is only supposed to be used when encryption is enabled then that's a separate bug. A failure in gcrypt shouldn't effect me.

**Comment by rubenk** [comment] 2016-08-29 08:18
@arader do you use signed packets? Looking at the code libgcrypt is only initialized when SecurityLevel is Encrypt or Sign.(https://github.com/collectd/collectd/blob/master/src/network.c#L2058)

**Comment by rubenk** [comment] 2016-08-29 08:24
@wtps0n thanks for your tests. Libgcrypt only asks for 32KB of secure memory when collectd starts up. If that succeeds, I have no doubt collectd will keep running.

To be honest, I don't think this is a libgcrypt issue either. It asks the OS for mlocked memory and if the OS won't give it, then the only reasonable thing it can do is to return an error. The same goes for collectd, we really don't want to send encrypted data when we're not sure the keys are secure.

Libgcrypt could handle the error a bit better, for which I've send them some patches a while ago.

In my opinion the only place this could really be fixed is in the FreeBSD kernel.

**Comment by arader** [comment] 2016-08-29 14:01
@rubenk this is all I have in my network config:

    <Plugin network>
        Server "10.0.1.21" "8096"
    </Plugin>

so I assume I'm not using any sort of network crypto.

Would this have been an issue in 5.5.1? I've been running collectd a long time and have never hit this before. I understand what you are saying about the issue not being "fixable" by collectd (after all, the OS isn't giving you memory) but it sure seems like this is a regression in collectd itself. On 5.5.1 everything was happy. On 5.5.2 without any config changes I got instant crashes.

Is libgcrypt a new dependency? If this is a regression due to this new dependency, what's the trade off here?

**Comment by rubenk** [comment] 2016-08-29 14:08
@arader libgcrypt is not a new dependency. We ignored the error in 5.5.1, see #1665.
While technically this is a regression (it seemed to work fine in 5.5.1 and now it doesn't), going back to just ignoring the error is really not an option.

**Comment by rubenk** [comment] 2016-08-29 14:30
@arander: I can reproduce your issue now. We call network_init_gcrypt() unconditionally from network_init (https://github.com/collectd/collectd/blob/master/src/network.c#L3442). Would you mind opening a separate issue for this? A workaround for you would be to rebuild collectd without support for libgcrypt.

**Comment by hume-github** [comment] 2016-08-29 14:32
Just as a note, this exact same error can be reproduced with collectd 5.5.2 built on Openindian (Illumos/Solaris).  The default system libgcrypt is rather old (1.5.4), and it attempts to lock down some memory, which isn't possible as non-root by default.  The error shows up as an EPERM in truss.

A simple workaround is to grant the running user the proc_lock_memory privilege, either via usermod or in  the SMF manifest starting collectd.

**Comment by arader** [comment] 2016-08-29 14:32
@rubenk I understand, but why is libgcrypt even being used if I'm not using crypto in my config?

It doesn't make sense to hit a failure condition causing a crash in a feature I'm not even using.

**Comment by rubenk** [comment] 2016-08-29 14:33
@arander, it shouldn't, that's why I asked you to open an issue.

**Comment by rubenk** [comment] 2016-08-29 14:36
@hume-github my guess is libgcrypt returns a "generic error" for this? I'm surprised your workaround works, when I checked the libgcrypt code it checked for root privileges itself. But perhaps it hits another code path on Solaris, or this code changed somewhat since 1.5.4.

In any case I think we should document this somewhere.

**Comment by arader** [comment] 2016-08-29 15:46
Sorry @rubenk, you submitted your discovery while I was typing mine up. I've opened #1902 

After that I went to disable the gcrypt flag from the port, but it turns out I already had it disabled, so in theory my collectd should already be built without libgcrypt...

@brd (or others) Is it possible that despite me unchecking the GCRYPT option on the FreeBSD port it still gets used because I already have libgcrypt on my system?

Is there a way to check what flags collectd was built with? I used _ldd_ and gcrypt wasn't mentioned, but I'm not sure if it's compiled as a static lib (and thus wouldn't show up anyway)

**Comment by rubenk** [comment] 2016-09-02 12:21
@arader No problem.
As for disabling libgcrypt, it is dynamically linked. If ldd on the collectd binary doesn't mention it, it is disabled.

**Comment by arader** [comment] 2016-09-02 22:33
@rubenk since ldd doesn't show any dependency on libgcrypt, how was I even hitting this bug? from reading this thread it's gcrypt that tries to lock memory, so if I'm not even using gcrypt...

Could there be some other place in collectd that locks memory?

**Comment by rubenk** [comment] 2016-09-04 12:05
@arader you'll have to tell me ;) Libgcrypt is the only thing that locks memory. If you haven't linked libgcrypt into your collectd binary I don't see how you could hit this.

**Comment by hume-github** [comment] 2016-09-05 01:26
Which binary are you using ldd against to check for libgcrypt?  collectd most likely isn't, but the network plugin may be.

```
$ ldd /opt/collectd/sbin/collectd | grep libgcrypt
$ ldd /opt/collectd/lib/collectd/network.so | grep libgcrypt
        libgcrypt.so.11 =>       /usr/lib/libgcrypt.so.11
```

**Comment by arader** [comment] 2016-09-05 14:26
@hume-github aha! makes sense, and yes, the network plugin has the dependency:

    libgcrypt.so.20 => /usr/local/lib/libgcrypt.so.20 (0x801830000)

I've been able to do some testing and here's what is happening. Despite me configuring FreeBSD's port of collectd to not use libgcrypt, the configure scripts must be seeing that I already have it on

**Comment by wtps0n** [comment] 2016-09-05 18:16
I did not test it on my FreeBSD server - I'm not sure that libgcrypt wil be used as dependency even when it is not included in port options. Maybe you are right...

But I think you can create your own pkg repo and build collectd without libgcrypt at all. That's will help :-)

**Comment by alexlinux** [comment] 2016-09-12 13:57
Hi,

I'm running Omnios r151014, collectd 5.5.2, libgcrypt-1.6.6

I have modified my collectd smf manifest:

```
        <exec_method
                type='method'
                name='start'
                exec='/etc/init.d/collectd-client start'
                timeout_seconds='60'>
           <method_context>
               <method_credential user='collectd' group='collectd' privileges='proc_lock_memory' />
           </method_context>
        </exec_method>

        <exec_method
                type='method'
                name='stop'
                exec='/etc/init.d/collectd-client stop'
                timeout_seconds='60'>
           <method_context>
               <method_credential user='collectd' group='collectd' privileges='proc_lock_memory' />
           </method_context>
        </exec_method>

```

```
#svccfg -s collectd listprop | grep pri
start/privileges                                  astring  proc_lock_memory
stop/privileges                                   astring  proc_lock_memory
```

But still having the same issue

Any ideas?

**Comment by rubenk** [comment] 2016-10-25 12:02
@alexlinux I'm afraid we can't be of much help with OmniOS. Perhaps just running collectd as root works for you?

**Comment by rubenk** [comment] 2016-10-25 12:04
It's been a few months now since I've sent patches for better error handling to the libgcrypt mailing list without any response.

Closing this issue since from our point of view we can't do anything about this.

**Closed by rubenk** 2016-10-25 12:04 UTC
Labels: bsd only, Bug, Pending feedback

**Comment by nimonimonimo** [comment] 2017-04-02 20:12
Is there currently any way to get encryption to work with collectd in FreeBSD?

**Comment by wtps0n** [comment] 2017-04-06 22:09
You mean "SecurityLevel Encrypt" instead of "SecurityLevel Sign"? I hope you've read the all comments. As I wrote in earlier comments I've changed sysctl vm.max_wired=1835008 and collectd is working correctly.

**Comment by phryk** [comment] 2017-05-08 22:32
I'm on FreeBSD-11 with ZFS+geli and I still run into the gcrypt init issue with 5.7.1,
even after upping vm.max_wired and rebooting the machine.

Additionally, the issue is still triggered even with SecurityLevel None
I thought [this issue](https://github.com/collectd/collectd/issues/1902) was already fixed in 5.5?

My installed gcrypt version is 1.7.6 if that's relevant; Any clarifications would be appreciated.

**Comment by wtps0n** [comment] 2017-05-10 11:40
Hmm, What can I say... Unfortuntely :-) I have no such problems. I've upgraded from 10.3-stable to 11.0-stable last week. And everything works correctly. 

Telling the truth I have my own pkg repo, so I'm building collectd with my options set, compiler flags etc. I did not check how collectd is built with official packages repo. Maybe that's the clue...

**Comment by phryk** [comment] 2017-05-10 12:23
I also have my own poudriere-based pkg repo, but I only got collectd to work by recompiling without gcrypt support.

Not a complete failure since it's only communicating through loopback devices (lo0 for host, lo1 for jails) and it should thus not be exposed, but I'd still like to have this fixed. Any additional info I can supply to help with that?

**Comment by wtps0n** [comment] 2017-05-10 13:13
If you have base and jails is it good idea to run collectd inside jail? For me it could be a problem, because you have to grow up vm.max_wired on "server side" and "client side". Maybe some sysctl setting does not work correctly inside jail? I'm not sure - maybe I'm wrong.

On my servers this communication is working on standalone servers, so vm.max_wired is working correctly. 

We can check my poudriere environment  - please check log file from build: http://uld.bsdserwis.com/pkg/data/11x64-default/2017-04-22_02h27m24s/logs/collectd5-5.7.1_1.log

**Comment by ec1oud** [comment] 2019-10-19 20:12
I'm still having this issue (found by googling) with collectd 5.8.1 on FreeBSD 12.0-RELEASE-p4.  It doesn't seem to matter what I set vm.max_wired to.  collectd runs, but in /var/log/messages I see

```
Oct 19 21:20:23 tsdb collectd[68387]: network plugin: gcry_control (GCRYCTL_INIT_SECMEM) failed: General error
Oct 19 21:20:23 tsdb collectd[68387]: network plugin: Cannot configure server socket with security: Failed to initialize crypto library.
Oct 19 21:20:23 tsdb collectd[68387]: network plugin: network_config_add_listen: sockent_init_crypto() failed.
```
I'm running it in a jail, and I need security because I want to expose this collectd instance to the Internet so that other systems in other places can log data to it.  I'm also running on zfs.  If it can't use gcrypt I don't think it's secure enough to use at all.

**Comment by wtps0n** [comment] 2019-10-24 11:52
I think the main problem is that you are running collectd inside jail. Please remember that inside jail there are some restrictions (i.e. /dev/bpf). So propably ypu have to allow collectd inside jail use mlock and alloc needed amount of memory.

I'm not an expert about this settings. I suppose sysctl -a will be helpful. Or seekeing freebsdforums? I've found sth like that: https://forums.freebsd.org/threads/mlock-2-in-jails.60841/ 

I'm hope my thought are helpful.
