### ISSUE TITLE
SMART plugin tries to read from loop devices

### ISSUE THREAD

**Issue by clarfon** [collectd/collectd#3314] opened 2019-10-16 00:42 UTC
*   Version of collectd: 5.9.0
*   Operating system / distribution: Arch Linux
*   Kernel version (if applicable): 5.2.17 (hardened)

My best guess is that libvirt is pre-allocating these and for some reason SMART isn't bailing immediately. My system log is basically flooded with these:

> `smart plugin: unable to open /dev/loop5`

I'd rather not filter which disks I scan because I'd like to scan all applicable disks, but erroring if `/dev/loopN` fails to provide SMART data seems excessive.

**Comment by rpv-tomsk** [comment] 2019-10-16 07:29
Scan is done by code:
```
enumerate = udev_enumerate_new(handle_udev);
  udev_enumerate_add_match_subsystem(enumerate, "block");
  udev_enumerate_add_match_property(enumerate, "DEVTYPE", "disk");
  udev_enumerate_scan_devices(enumerate);
  devices = udev_enumerate_get_list_entry(enumerate);
  udev_list_entry_foreach(dev_list_entry, devices) { ... }
```

This code checks for subsystem and DEVTYPE property only.
Loop devices match these checks:
```
# udevadm info -q all --name=/dev/loop0
P: /devices/virtual/block/loop0
N: loop0
E: DEVNAME=/dev/loop0
E: DEVPATH=/devices/virtual/block/loop0
E: DEVTYPE=disk
E: MAJOR=7
E: MINOR=0
E: SUBSYSTEM=block
E: UDEV_LOG=3
E: USEC_INITIALIZED=9466064476310
```

So, behaviour is expected.

>I'd rather not filter

I think, ignoring by regex `Disk "/loop[0-9]+/"` should avoid logging error message.

**Comment by mrunge** [comment] 2019-10-23 07:03
Closing this, as it seems to be answered. Please re-open, if you think it's necessary.

**Closed by mrunge** 2019-10-23 07:03 UTC

**Comment by PhilippWendler** [comment] 2022-05-09 13:51
Since #3510 it seems that the filtering is now based on the serial of the device instead of the name if `UseSerial true` is set. How can I filter loop devices in this situation? It seems they have no serial.

**Comment by PhilippWendler** [comment] 2023-06-26 09:42
@mrunge This problem still exists with `UseSerial true`. I noticed that the smart plugin already depends on the naming of the device nodes here:
https://github.com/collectd/collectd/blob/9369ed71450430266ebd7ca410022c2b1b548fb4/src/smart.c#L574

Would it be acceptable to similarly hard-code a filter for `loop` devices? Or at least turn the error message into a debug message if it is a loop device?

**Comment by PhilippWendler** [comment] 2024-01-15 08:12
@mrunge How to filter loop devices in combination with `UseSerial true`? A hint how to do this would be really appreciated.

**Comment by LHozzan** [comment] 2024-04-13 21:26
@PhilippWendler Problem is described [here](https://github.com/collectd/collectd/issues/3856). The issue is still opened.
I hope it helps.

**Comment by eero-t** [comment] 2024-04-16 09:26
> @PhilippWendler Problem is described [here](https://github.com/collectd/collectd/issues/3856). The issue is still opened. 

Proposing a fix in a pull request could help...
