### ISSUE TITLE
AIX 7.2 fails to load any plugins

### ISSUE THREAD

**Issue by SkyMoCo** [collectd/collectd#2677] opened 2018-02-08 17:10 UTC
*   Version of collectd:  collectd 5.8.0.git
*   Operating system / distribution:   AIX 7.2

Complied from scratch using gcc (GCC) 6.3.0

## Actual behavior

No plugins will load even though they all exist in the plugins directory.
$ /opt/collectd/sbin/collectd -T
plugin_load: Could not find plugin "logfile" in /opt/collectd/lib/collectd

sysnim23@root:/ # ls -l /opt/collectd/lib/collectd/logfile*
-rwxr-xr-x    1 root     system         5012 Feb  8 09:36 /opt/collectd/lib/collectd/logfile.a
-rwxr-xr-x    1 root     system          896 Feb  8 09:36 /opt/collectd/lib/collectd/logfile.la

**Comment by trustchk** [comment] 2018-03-07 13:49
Does https://github.com/collectd/collectd/issues/2361#issuecomment-364236341 solve the problem for you?

**Comment by rpv-tomsk** [comment] 2018-05-25 02:32
Closed as it is mostly duplicate of #2361 and no feedback received.

**Closed by rpv-tomsk** 2018-05-25 02:32 UTC
Labels: Pending feedback, aix only
