### ISSUE TITLE
Please use pkg-config instead of libgcrypt-config to locate libgcrypt

### ISSUE THREAD

**Issue by bzed** [collectd/collectd#4315] opened 2024-06-27 11:44 UTC
Forwarded from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1070905

Please switch from using libgcrypt-config to pkg-config to locate
libgcrypt. libgcrypt-config will be dropped in the next libgcrypt major
release.

(Please do not switch from collectd's handwritten detection code to
AM_PATH_LIBGCRYPT() unless you invoke AM_PATH_GPG_ERROR() first. The
former currently requires the latter to work without libgcrypt-config.
Just go for pkg-config instead.)

**Comment by eero-t** [comment] 2024-06-27 13:55
Could you make also a PR for that?

**Comment by bzed** [comment] 2024-06-27 14:00
> Could you make also a PR for that?

no.

**Comment by xnox** [comment] 2024-07-30 18:58
Duplicate of https://github.com/collectd/collectd/issues/4310

**Comment by eero-t** [comment] 2024-08-19 11:02
> Duplicate of #4310

Thanks, closing this one (both were reported by @bzed).

**Closed by eero-t** 2024-08-19 11:02 UTC
