### ISSUE TITLE
(Suggested) future (fork) of collectd

### ISSUE THREAD

**Issue by systemcrash** [collectd/collectd#3885] opened 2021-06-18 12:04 UTC
Hello everyone.

@mrunge 
@bkjg
@jkohen
@octo
@pyr
@tokkee

Given the absence of key maintainers of this project, and inability to merge PRs or manage CI infra, I suggest forking the project to a new org/repo space.  ( I do note that @octo or someone purporting to be said person has contributed to [activity on github recently](https://github.com/octo/portfolio-mcmc). )

With perhaps the following modifications:

- some kind of quorum system whereby there at least two who approve are necessary, but e.g. at least 4 can approve. 
- if one approver has been silent/absent for a month without prior notification, that an additional member can be promoted to approver
- some mechanism to promote community members to org members

Basically, ideas which help keep the structure intact and moving. 

Given that the world has been ravaged by a deadly pandemic, plus other normal daily life events (got busy with life, depressed, etc), it's possible and reasonable to make assumptions about some of the founding members. Should they reappear, it is possible for them to join in once more.

https://www.mail-archive.com/collectd@verplant.org/msg04196.html

What limitations are there to performing this move today? Funding/financials which pay for e.g. CI services?
Are there any obvious candidates to help in this leading role? Volunteers?

I personally like github, and would prefer for things to remain on github, but if there is another path of least resistance - the project would do well to go that way. 

Alternatively, @octo if you're around 👋 , consider promoting others with more permissions to move this project forward.

**Comment by mrunge** [comment] 2021-06-18 15:07
Hi,
I am very much twofold about this. 

While I would prefer to keep the project alive under the current github organization, you already mentioned the issues with CI for now about 8 months (or so). 

By creating a fork, we'd basically split the community and may end up with two unmaintained forks. But let's think positive. I'd also like to be able to merge the two forks back when the time has come.

@octo granted about 20 people merge rights a little over a year ago. We have seen only a single, maybe two or three persons stepping up and doing one or more reviews and also some PRs/rebases. On the other side, collectd has been blessed with a HUGE number of PRs (open). That is good and bad at the same time. Good, because it shows that people cared so much for the project that they actually either fixed an issue or contributed a plugin. I am very grateful for that. It also puts a bit of workload, the people looking at this can be easily counted with one hand. 

Maybe you are right and the time has come to actually go and fork the project. Would you be willing to step up and do reviews?

For starters, my colleague @elfiesmelfie has already a PR open on https://github.com/collectd-mirror/collectd/pull/1 to replace the current defunct travis ci with github actions. That could be *one* alternative.

I also like your ideas of foundation to keep the project alive and healthy. I'd also like to note this is not the first opened issue, for example see https://github.com/collectd/collectd/issues/3863

While we should have in theory a good number of volunteers to do some work, reality showed we have not.

**Comment by elfiesmelfie** [comment] 2021-06-23 13:41
In this case, I don't see an alternative to forking the project if collectd is to stay alive.
Code can't be merged to main due to the travis issue, at the moment, and without action, the project can't move forward.
The fork is meant to be temporary, and if/when the issue is resolved, we would try to merge back in changes to [collectd/collectd](http://github.com/collectd/collectd).

At the very least, we need a way to provide bug fixes.  IMO any mirror (such as [collectd-mirror/collectd](https://github.com/collectd-mirror/collectd/) should be limited to bug fixes for collectd-5.x.
Contributions to collectd-6, I think, should continue here, as  fixes are mergable at the moment. later, some decision will have to be made about what to do about merging collectd-6 into main. Hopefully, by then, we will have resolved the travis issue.

I am going to try to improve the CI as much as possible, continuing the work started in [collectd-mirror/collectd#1](https://github.com/collectd-mirror/collectd/pull/1) to make the workload a little easier for reviewers. I'm open to any feedback about what would be useful. Eventually, I would like to contribute this back to collectd/collectd, in place of the travis jobs.

**Comment by systemcrash** [comment] 2021-06-30 17:40
I don't mind performing reviews - although my C skills may miss bugs on that front. 

Forking might not be ideal, but it will keep the project alive. I propose a new name `recollectd` as a project name only. For all other intents and purposes, `collectd` is good, but might need changing if distros that package this want to pick up on the fork. 

What can be done first here in this repo? Anything? Or do permissions lack for CI?

Otherwise: fork.

**Comment by elfiesmelfie** [comment] 2021-06-30 19:05
My C skills leave a lot to be desired too. But I am willing to help with test automation to make reviews easier. In my opinion, this is important to reduce the load on reviewers. There were discussions [a while back](https://collectd.org/wiki/index.php/MinutesFeb3rd20) about improving the CI, and combining the tests that various people are running in different platforms. This would mean sharing the actual tests for others to run and/or reporting test results from different lab (such as with github runners), which is something we can try and push for again if we get to a point where we can merge changes. This would also be pretty useful for collectd-6 migration to ensure equivalency between the versions. But I digress, main point is we can have more contribution than just C code.

Regarding CI permissions:
The CI is set up **for the main branch** in this repo so that travis needs to run and pass before a change can be merged to the main branch.
Unfortunately, Travis-CI is no longer running, due to a change late last year where they moved to a credit-based model. 
We lack the permissions to remove the Travis-CI app from the repo (admin permission is needed, and only one person has that power), so we can't disable Travis-CI and unblock merging to the main branch.

If distros want to pick this up, renaming the repo might cause issues with automation, especially if it's a temporary workaround to allow bug fixes for 5.x, and will continue to cause issues with users that try to install. That's my thoughts on it, but would need more input from those with more packaging and distribution experience than me.

**Comment by mrunge** [comment] 2021-07-02 06:05
> I don't mind performing reviews - although my C skills may miss bugs on that front.
> 
> Forking might not be ideal, but it will keep the project alive. I propose a new name `recollectd` as a project name only. For all other intents and purposes, `collectd` is good, but might need changing if distros that package this want to pick up on the fork.
> 
> What can be done first here in this repo? Anything? Or do permissions lack for CI?
> 
> Otherwise: fork.

Thank you for your offer. Permissions lack to fix CI in this repo. 

Emma is working on https://github.com/collectd-mirror/collectd/pull/1

**Comment by eero-t** [comment] 2021-09-06 11:58
@mrunge Is there any update on what are the plans with collectd-mirror, and whether there's any progress in getting collectd moving forward again?

**Comment by mrunge** [comment] 2021-09-06 12:23
At the moment, we can move on here with this organization and upstream collectd/collectd; there is no need for a fork. I was given permissions and can modify CI settings.

**Closed** 2021-09-06 12:23 UTC

**Comment by systemcrash** [comment] 2021-09-07 20:38
Let me know if there are any casual things we can do to help/speed up some of these PRs

**Comment by mrunge** [comment] 2021-09-08 11:52
@systemcrash thank you for your kind offer. You can try changes out, like @elfiesmelfie did a couple of times already, you can look at proposed changes and comment on that. All of that will help with moving things forward.
