### ISSUE TITLE
turbostat: Ignoring trailing garbage

### ISSUE THREAD

**Issue by ConiKost** [collectd/collectd#2365] opened 2017-07-17 10:08 UTC
*   Version of collectd: 4.7.2
*   Operating system / distribution: Gentoo

When I do enable turbostat, the plugin seems to work, but it logs during start some warnings. I don't know, if this is supposed to do so?

Jul 17 11:56:25 [collectd] parse_value: Ignoring trailing garbage "-11" after derive value. Input string was "0-11".
Jul 17 11:56:25 [collectd] parse_value: Ignoring trailing garbage ",6" after derive value. Input string was "0,6".
Jul 17 11:56:25 [collectd] parse_value: Ignoring trailing garbage "-11" after derive value. Input string was "0-11".
Jul 17 11:56:25 [collectd] parse_value: Ignoring trailing garbage ",7" after derive value. Input string was "1,7".
Jul 17 11:56:25 [collectd] parse_value: Ignoring trailing garbage "-11" after derive value. Input string was "0-11".
Jul 17 11:56:25 [collectd] parse_value: Ignoring trailing garbage ",8" after derive value. Input string was "2,8".
Jul 17 11:56:25 [collectd] parse_value: Ignoring trailing garbage "-11" after derive value. Input string was "0-11".
Jul 17 11:56:25 [collectd] parse_value: Ignoring trailing garbage ",9" after derive value. Input string was "3,9".
Jul 17 11:56:25 [collectd] parse_value: Ignoring trailing garbage "-11" after derive value. Input string was "0-11".
Jul 17 11:56:25 [collectd] parse_value: Ignoring trailing garbage ",10" after derive value. Input string was "4,10".
Jul 17 11:56:25 [collectd] parse_value: Ignoring trailing garbage "-11" after derive value. Input string was "0-11".
Jul 17 11:56:25 [collectd] parse_value: Ignoring trailing garbage ",11" after derive value. Input string was "5,11".
Jul 17 11:56:25 [collectd] parse_value: Ignoring trailing garbage "-11" after derive value. Input string was "0-11".
Jul 17 11:56:25 [collectd] parse_value: Ignoring trailing garbage ",6" after derive value. Input string was "0,6".
Jul 17 11:56:25 [collectd] parse_value: Ignoring trailing garbage "-11" after derive value. Input string was "0-11".
Jul 17 11:56:25 [collectd] parse_value: Ignoring trailing garbage ",7" after derive value. Input string was "1,7".
Jul 17 11:56:25 [collectd] parse_value: Ignoring trailing garbage "-11" after derive value. Input string was "0-11".
Jul 17 11:56:25 [collectd] parse_value: Ignoring trailing garbage ",8" after derive value. Input string was "2,8".
Jul 17 11:56:25 [collectd] parse_value: Ignoring trailing garbage "-11" after derive value. Input string was "0-11".
Jul 17 11:56:25 [collectd] parse_value: Ignoring trailing garbage ",9" after derive value. Input string was "3,9".
Jul 17 11:56:25 [collectd] parse_value: Ignoring trailing garbage "-11" after derive value. Input string was "0-11".
Jul 17 11:56:25 [collectd] parse_value: Ignoring trailing garbage ",10" after derive value. Input string was "4,10".
Jul 17 11:56:25 [collectd] parse_value: Ignoring trailing garbage "-11" after derive value. Input string was "0-11".
Jul 17 11:56:25 [collectd] parse_value: Ignoring trailing garbage ",11" after derive value. Input string was "5,11".

**Comment by octo** [comment] 2017-10-25 06:54
Hi @ConiKost,

version 4.7 is ancient and we no longer provide support for it. Is this problem still present in 5.7?

Best regards,
—octo

**Comment by ConiKost** [comment] 2017-10-26 19:43
@octo, yes, it's still present. I am using currently 5.7.2.

**Comment by dword1511** [comment] 2018-07-22 23:45
Same phenomenon for `collectd` 5.8.0.git (Debian), but I did not test whether it is caused by `turbostat`.
Corresponding log:
```
Jul 22 16:39:46 czhang-laptop systemd[1]: Starting Statistics collection and monitoring daemon...
Jul 22 16:39:46 czhang-laptop collectd[28690]: plugin_load: plugin "syslog" successfully loaded.
Jul 22 16:39:46 czhang-laptop collectd[28690]: plugin_load: plugin "battery" successfully loaded.
Jul 22 16:39:46 czhang-laptop collectd[28690]: plugin_load: plugin "contextswitch" successfully loaded.
Jul 22 16:39:46 czhang-laptop collectd[28690]: plugin_load: plugin "cpu" successfully loaded.
Jul 22 16:39:46 czhang-laptop collectd[28690]: plugin_load: plugin "cpufreq" successfully loaded.
Jul 22 16:39:46 czhang-laptop collectd[28690]: plugin_load: plugin "df" successfully loaded.
Jul 22 16:39:46 czhang-laptop collectd[28690]: plugin_load: plugin "disk" successfully loaded.
Jul 22 16:39:46 czhang-laptop collectd[28690]: plugin_load: plugin "dns" successfully loaded.
Jul 22 16:39:46 czhang-laptop collectd[28690]: plugin_load: plugin "entropy" successfully loaded.
Jul 22 16:39:46 czhang-laptop collectd[28690]: plugin_load: plugin "interface" successfully loaded.
Jul 22 16:39:46 czhang-laptop collectd[28690]: plugin_load: plugin "irq" successfully loaded.
Jul 22 16:39:46 czhang-laptop collectd[28690]: plugin_load: plugin "load" successfully loaded.
Jul 22 16:39:46 czhang-laptop collectd[28690]: plugin_load: plugin "memory" successfully loaded.
Jul 22 16:39:46 czhang-laptop collectd[28690]: plugin_load: plugin "network" successfully loaded.
Jul 22 16:39:46 czhang-laptop collectd[28690]: plugin_load: plugin "processes" successfully loaded.
Jul 22 16:39:46 czhang-laptop collectd[28690]: plugin_load: plugin "python" successfully loaded.
Jul 22 16:39:46 czhang-laptop collectd[28690]: plugin_load: plugin "rrdtool" successfully loaded.
Jul 22 16:39:46 czhang-laptop collectd[28690]: plugin_load: plugin "sensors" successfully loaded.
Jul 22 16:39:46 czhang-laptop collectd[28690]: plugin_load: plugin "swap" successfully loaded.
Jul 22 16:39:46 czhang-laptop collectd[28690]: plugin_load: plugin "tcpconns" successfully loaded.
Jul 22 16:39:46 czhang-laptop collectd[28690]: plugin_load: plugin "thermal" successfully loaded.
Jul 22 16:39:46 czhang-laptop collectd[28690]: plugin_load: plugin "turbostat" successfully loaded.
Jul 22 16:39:46 czhang-laptop collectd[28690]: plugin_load: plugin "uptime" successfully loaded.
Jul 22 16:39:46 czhang-laptop collectd[28690]: plugin_load: plugin "users" successfully loaded.
Jul 22 16:39:46 czhang-laptop collectd[28690]: plugin_load: plugin "vmem" successfully loaded.
Jul 22 16:39:46 czhang-laptop collectd[28690]: Found a configuration for the `ntpd' plugin, but the plugin isn't loaded or didn't register a configuration callback.
Jul 22 16:39:46 czhang-laptop collectd[28690]: Found a configuration for the `ntpd' plugin, but the plugin isn't loaded or didn't register a configuration callback.
Jul 22 16:39:46 czhang-laptop collectd[28690]: Systemd detected, trying to signal readyness.
Jul 22 16:39:46 czhang-laptop collectd[28690]: cpufreq plugin: Found 8 CPUs
Jul 22 16:39:46 czhang-laptop systemd[1]: Started Statistics collection and monitoring daemon.
Jul 22 16:39:46 czhang-laptop collectd[28690]: parse_value: Ignoring trailing garbage "-7" after derive value. Input string was "0-7".
Jul 22 16:39:46 czhang-laptop collectd[28690]: parse_value: Ignoring trailing garbage ",4" after derive value. Input string was "0,4".
Jul 22 16:39:46 czhang-laptop collectd[28690]: parse_value: Ignoring trailing garbage "-7" after derive value. Input string was "0-7".
Jul 22 16:39:46 czhang-laptop collectd[28690]: parse_value: Ignoring trailing garbage ",5" after derive value. Input string was "1,5".
Jul 22 16:39:46 czhang-laptop collectd[28690]: parse_value: Ignoring trailing garbage "-7" after derive value. Input string was "0-7".
Jul 22 16:39:46 czhang-laptop collectd[28690]: parse_value: Ignoring trailing garbage ",6" after derive value. Input string was "2,6".
Jul 22 16:39:46 czhang-laptop collectd[28690]: parse_value: Ignoring trailing garbage "-7" after derive value. Input string was "0-7".
Jul 22 16:39:46 czhang-laptop collectd[28690]: parse_value: Ignoring trailing garbage ",7" after derive value. Input string was "3,7".
Jul 22 16:39:46 czhang-laptop collectd[28690]: parse_value: Ignoring trailing garbage "-7" after derive value. Input string was "0-7".
Jul 22 16:39:46 czhang-laptop collectd[28690]: parse_value: Ignoring trailing garbage ",4" after derive value. Input string was "0,4".
Jul 22 16:39:46 czhang-laptop collectd[28690]: parse_value: Ignoring trailing garbage "-7" after derive value. Input string was "0-7".
Jul 22 16:39:46 czhang-laptop collectd[28690]: parse_value: Ignoring trailing garbage ",5" after derive value. Input string was "1,5".
Jul 22 16:39:46 czhang-laptop collectd[28690]: parse_value: Ignoring trailing garbage "-7" after derive value. Input string was "0-7".
Jul 22 16:39:46 czhang-laptop collectd[28690]: parse_value: Ignoring trailing garbage ",6" after derive value. Input string was "2,6".
Jul 22 16:39:46 czhang-laptop collectd[28690]: parse_value: Ignoring trailing garbage "-7" after derive value. Input string was "0-7".
Jul 22 16:39:46 czhang-laptop collectd[28690]: parse_value: Ignoring trailing garbage ",7" after derive value. Input string was "3,7".
Jul 22 16:39:46 czhang-laptop collectd[28690]: Initialization complete, entering read-loop.
Jul 22 16:39:46 czhang-laptop collectd[28690]: tcpconns plugin: Reading from netlink succeeded. Will use the netlink method from now on.
```
```
$ collectd -h
Usage: collectd [OPTIONS]

Available options:
  General:
    -C <file>       Configuration file.
                    Default: /etc/collectd/collectd.conf
    -t              Test config and exit.
    -T              Test plugin read and exit.
    -P <file>       PID-file.
                    Default: /var/run/collectd.pid
    -f              Don't fork to the background.
    -B              Don't create the BaseDir
    -h              Display help (this message)

Builtin defaults:
  Config file       /etc/collectd/collectd.conf
  PID file          /var/run/collectd.pid
  Plugin directory  /usr/lib/collectd
  Data directory    /var/lib/collectd

collectd 5.8.0.git, http://collectd.org/
by Florian octo Forster <octo@collectd.org>
for contributions see `AUTHORS'
```
```
$ dpkg --list collectd
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                                          Version                             Architecture                        Description
+++-=============================================================-===================================-===================================-================================================================================================================================
ii  collectd                                                      5.8.0-5.1                           amd64                               statistics collection and monitoring daemon
```

**Comment by mrunge** [comment] 2018-08-14 13:03
I can reproduce this issue with collectd-5.8.0 (on RHEL 7).

**Comment by MrStupnikov** [comment] 2019-04-04 12:53
Folks, any plans for this fix?

**Comment by rpv-tomsk** [comment] 2019-04-04 15:13
Anybody has to work on this. Can you?

For this to be fixed, at first we need to get more details about problem cause.
For example, we need to get content which causes error message.
That content came from following files:
```
# cat turbostat.c |grep -A 1 parse_int
    ret = parse_int_file(
        "/sys/devices/system/cpu/cpu%d/topology/physical_package_id", i);
--
    ret = parse_int_file("/sys/devices/system/cpu/cpu%d/topology/core_id", i);
    if (ret < 0)
--
    ret = parse_int_file(
        "/sys/devices/system/cpu/cpu%d/topology/core_siblings_list", i);
--
    ret = parse_int_file(
        "/sys/devices/system/cpu/cpu%d/topology/thread_siblings_list", i);
```

When we will have content example, then we have to think how to fix the issue.

**Comment by sunkuranganath** [comment] 2019-04-09 20:25
Looking to find the right owner at Intel. Will keep this forum posted.

**Comment by ConiKost** [comment] 2019-04-20 22:02
The problem lies within ```parse_int_file```. It expects a single int, but ````/sys/devices/system/cpu/cpu%d/topology/core_siblings_list``` doesn't deliver a single int, instead, a string list, like ```0-7``` in my case.

```human-readable list of cpuX's hardware threads within the same physical_package_id.```

**Comment by mrunge** [comment] 2019-11-08 08:17
https://github.com/collectd/collectd/pull/3340 was merged to master

**Closed by mrunge** 2019-11-08 08:17 UTC
Labels: Pending feedback
