### ISSUE TITLE
Plugin syslog failed to handle option LogLevel, return code: 1

### ISSUE THREAD

**Issue by Whissi** [collectd/collectd#3236] opened 2019-07-29 19:30 UTC
*   Version of collectd: 5.9.1
*   Operating system / distribution: Gentoo
*   Kernel version (if applicable): 4.9.186

## Expected behavior

Plugin should load.

## Actual behavior

Plugin doesn't load and collectd will log the error
```
Plugin syslog failed to handle option LogLevel, return code: 1
```

## Steps to reproduce

*   Compile collectd with syslog plugin
*   Try to load syslog plugin like
```
LoadPlugin "syslog"
<Plugin "syslog">
    LogLevel    "DEBUG"
    NotifyLevel "OKAY"
</Plugin>
```

**Comment by faxm0dem** [comment] 2019-07-29 22:03
this is a duplicate of #3232

**Comment by faxm0dem** [comment] 2019-07-29 22:07
@whissi can you please verify that https://github.com/collectd/collectd/pull/3237 fixes this?

**Comment by Whissi** [comment] 2019-07-30 10:00
With the fix I get
```
plugin_load: plugin "syslog" successfully loaded.
syslog: invalid loglevel [DEBUG] defaulting to 'info'
Plugin syslog failed to handle option LogLevel, return code: 1
```

**Comment by Whissi** [comment] 2019-07-30 10:07
Interesting, doc says
> Currently, using LogLevel "debug" is only valid if the collectd sources are built with -DCOLLECT_DEBUG at compilation time.

and indeed, I compiled with `--disable-debug`. After recompiling with `--enable-debug` it works. Funny, was working fine with v5.8.x for some time.

**Comment by faxm0dem** [comment] 2019-07-30 10:16
ah yes, this was something that was forgotten in #3182 we should return 0 in that case.
I'll make a new PR to fix that

**Closed** 2019-07-30 12:15 UTC

**Comment by mrunge** [comment] 2019-08-06 11:09
see https://github.com/collectd/collectd/pull/3237.
