### ISSUE TITLE
ping plugin does not scale

### ISSUE THREAD

**Issue by YmrDtnJu** [collectd/collectd#2094] opened 2016-12-09 16:11 UTC
*   Version of collectd: 5.6.1 (but the problem exists since I started using collectd)
*   Operating system / distribution: Debian Wheezy

## Expected behavior
The ping plugin should be able ping a lot of hosts and return the correct statistics.

## Actual behavior
The ping plugin pings the hosts, but fails to return correct statistics because it misses echo reply pakets. We have about 300 hosts to ping. The system that hosts collectd is a highend server with 20 Gbit/s network connection. Additionally, I can ping hosts with the normal ping command on the console without any paket loss at the same time when collectd reports high paket loss. We have a testsystem on another machine that has the same problem. It seems, the plugin pings all hosts at the same time and is not able to receice the reply pakets. I tried to change the number of Read and WriteThreads, but that did not work.

collectd as well as liboping are self compiled for our debian instrastructure. I don't think, this is the source of the problem, because I also tried the same number of hosts with a collectd from a gentoo system with the same results.

At least the documentation should tell the user, that they can only configure a small number of hosts to ping if they require correct results.

Maybe a solution would be not to ping all hosts at the same time but to ping hosts in steps of 10 or 20 with a pause of some milliseconds in between each step.

## Steps to reproduce
*   Configure more than a handfull hosts to ping.

**Comment by rpv-tomsk** [comment] 2017-04-02 04:54
@octo, what do you think about this issue? What is the cause of problem?

**Comment by rpv-tomsk** [comment] 2017-04-02 15:58
@YmrDtnJu, can you please show your configuration (Interval, Timeout, Size, MaxMissed)?

**Comment by octo** [comment] 2017-04-05 11:19
There's a pull request on *liboping* (octo/liboping#11) which improves performance. Unfortunately, it's based on an old version and needs works to be rebased on top of `master`. I don't have time to look into that currently, so any help would be more than welcome :)

**Comment by rpv-tomsk** [comment] 2017-08-05 10:22
@YmrDtnJu, this issue should be fixed in new `liboping` release, liboping-1.10.0.
Can you please confirm that?

**Comment by YmrDtnJu** [comment] 2017-08-09 20:49
I am sorry, but I cannot, because I don't work for that company anymore and don't have any environment to test it. I may ask someone to test it, but it will take at least a week. He is currently on vacation.

**Comment by octo** [comment] 2017-08-28 12:40
Alright, closing as obsolete then.

**Closed by octo** 2017-08-28 12:40 UTC
Labels: Pending feedback
