### ISSUE TITLE
collectd is killed by collectdmon while running java org.collectd.java.GenericJMX plugin 

### ISSUE THREAD

**Issue by anryko** [collectd/collectd#2321] opened 2017-06-20 17:55 UTC
*   Version of collectd: 5.4.0, 5.5.2
*   Operating system / distribution: Ubuntu 14.04 LTS

## Expected behavior

 java org.collectd.java.GenericJMX plugin is working.

## Actual behavior
collectd process is killed by collectdmon
```
2017-06-20T19:50:20.172523+02:00 hostname collectdmon[16225]: Warning: collectd was terminated by signal 11 (core dumped)
2017-06-20T19:50:20.172532+02:00 hostname collectdmon[16225]: Error: collectd is respawning too fast - disabled for 300 seconds
```

## Steps to reproduce
Update Ubuntu 14.04 LTS to latest version and run collectd with example plugin configuration
```
LoadPlugin java

<Plugin java>
    JVMArg "-verbose:jni"
    JVMArg "-Djava.class.path=/usr/share/collectd/java/collectd-api.jar:/usr/share/collectd/java/generic-jmx.jar"
    LoadPlugin "org.collectd.java.GenericJMX"
</Plugin>
```

**Comment by ennioj** [comment] 2017-06-21 09:01
Hi, 
same problem here(same versions as above), I wanted to add a hint: 
On systems with:  
$ uname -r
3.13.0-119-generic
Works
 the update to 3.13.0-121-generic brakes it

**Comment by nanjj** [comment] 2017-06-26 03:42
Looks it's caused by kernel issues here:
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1699772

**Comment by pcummins** [comment] 2017-06-27 04:34
I can second this bug impacts CentOS 7.3 with CollectD 5.7.1 and Sun Java 8u131. Introduced with 3.10.0-514.21.2.el7 and resolved by rolling back to 3.10.0-514.21.1.el7.x86_64.

**Comment by iwan41** [comment] 2017-06-28 11:38
Use: -Xss1280k to workaround this issue until kernel patch will be release (workaround is in @nanjj link).

Try
`LoadPlugin java

<Plugin java>
    JVMArg "-verbose:jni"
   JVMArg "-Xss1280k"
    JVMArg "-Djava.class.path=/usr/share/collectd/java/collectd-api.jar:/usr/share/collectd/java/generic-jmx.jar"
    LoadPlugin "org.collectd.java.GenericJMX"
</Plugin>`

**Comment by rubenk** [comment] 2017-06-29 16:35
Closing since this is not a collectd issue.

**Closed by rubenk** 2017-06-29 16:35 UTC
Labels: Pending feedback

**Comment by jbehrends** [comment] 2017-07-13 17:29
After upgrading a CentOS 6.x system to latest 6, I just ran into this issue.  
Here are my versions:

CentOS release 6.9 (Final)
kernel: 2.6.32-696.3.2.el6.x86_64
java version "1.8.0_92"
collectd 5.7.2

**Comment by rubenk** [comment] 2017-07-14 11:17
@jbehrends there's a newer kernel for CentOS 6 that should solve it:

* Fri Jun 30 2017 Denys Vlasenko <dvlasenk@redhat.com> [2.6.32-696.6.3.el6]
- [mm] allow JVM to implement its own stack guard pages (Larry Woodman) [1466667 1464237]
- [mm] enlarge stack guard gap (Larry Woodman) [1466667 1464237]
- Revert: [mm] enlarge stack guard gap (Larry Woodman) [1466667 1464237]
