### ISSUE TITLE
write_graphite plugin may cause many NaN values

### ISSUE THREAD

**Issue by dllhlx** [collectd/collectd#1174] opened 2015-07-31 07:20 UTC
these days, i use collectd-snmp plugin to collect net devices data, but i catch much NaN value from data to send to  graphite with tcpdump tool, so I read the collectd source code, then i found a suspected problem:
in src/write_graphite.c function->format_graphite()，this expression `rates = uc_get_rate (ds, vl);` if rates contain NaN value, then gr_format_values() may create a character string which is NaN。 because  in gr_format_values() function,  this expression  `if (rates != NULL)` can not filter out NaN in rates but rates is not Null, then `BUFFER_ADD ("%f", rates[ds_num]);` whill create NaN string。besides，I Comment out this section 
```c
/* else if (rates != NULL)
        BUFFER_ADD ("%f", rates[ds_num]); */
```
then re-compiling, run collectd, then NaN gone.

**Comment by dllhlx** [comment] 2015-07-31 07:29
@octo  Please help confirm.. thx

**Comment by yolkov** [comment] 2015-11-17 13:34
+1
whisper-fetch /var/lib/graphite/whisper/collectd/ns02/dns/dns_octets/responses.wsp | grep -i nan
1447696380      nan
1447758600      nan

**Comment by octo** [comment] 2015-11-18 08:37
Yes, collectd will happily forward NaN values to Graphite.

The rate calculation will result in NaN when only a single data point is available, for example. This branch is only taken when the *StoreRates* option is set to *true*, so commenting out that part of code and recompiling is unnecessary, as you can simply change the configuration to turn conversion to rates off:
```
<Plugin "write_graphite">
  …
  StoreRates false
</Plugin>
```

Closing this as **working as intended**.

**Closed by octo** 2015-11-18 08:37 UTC

**Comment by yolkov** [comment] 2015-11-18 09:03
If set "StoreRates false" and integer counter(example dns plugin) have limit 2^32, after reached limit counter starts from the begining and graphite graphs become incorect.

**Comment by mfournier** [comment] 2015-11-18 10:16
> ```
> value
> A numeric or null value. Values are stored as double-precision floats. Values are parsed using the python float() constructor and can also be None (null). The range and precision of values is system dependent and can be found by executing (with Python 2.6 or later):: python -c ‘import sys; print sys.float_info’
> ```

Arguably, NaN is a valid float value according to https://en.wikipedia.org/wiki/NaN. I doubt python would choke over that. The fact it gets stored in whisper files proves graphite doesn't neither. If this is an issue for the frontend displaying graphs, maybe a fix should be worked on at this level ?

**Comment by octo** [comment] 2015-11-21 07:23
@yolkov right, the overflow behavior is the difference between `DERIVE` and `COUNTER`.

 *  When `DERIVE` overflows, it will result in a *huge* negative spike, something like -4059923958. Most `DERIVE` metrics therefore have a *minimum* value of zero (0) to simply discard these spikes. The advantage is that the same mechanism works for counter resets.
 *  When `COUNTER` overflows, it will try to determine the size of the counter (32 bit or 64 bit) and will try to calculate a rate taking the overflow into account. No sample is discarded. However, the huge disadvantage is that *counter resets* cause a huge positive spike, which is very hard to filter out.

With *StoreRates true* collectd will do this conversion instead of Graphite. I have no idea how Graphite is dealing with this, but I'd consider collectd's behavior correct.

Best regards,
—octo
