### ISSUE TITLE
CollectD from master does not compile on Solaris

### ISSUE THREAD

**Issue by dago** [collectd/collectd#1068] opened 2015-06-09 11:53 UTC
The current head of Git master fails on Solaris with this error:
```
  CC       utils_dns.lo
utils_dns.c: In function ‘handle_ipv6’:
utils_dns.c:479:17: error: storage size of ‘ext_hdr’ isn’t known
  struct ip6_ext ext_hdr;
                 ^
utils_dns.c:483:24: error: invalid application of ‘sizeof’ to incomplete type ‘struct ip6_ext’
  if ((offset + sizeof (struct ip6_ext)) > (unsigned int)len)
                        ^
utils_dns.c:490:52: error: invalid application of ‘sizeof’ to incomplete type ‘struct ip6_ext’
  memcpy (&ext_hdr, (char *) ipv6 + offset, sizeof (struct ip6_ext));
                                                    ^
utils_dns.c:479:17: error: unused variable ‘ext_hdr’ [-Werror=unused-variable]
  struct ip6_ext ext_hdr;
                 ^
cc1: all warnings being treated as errors
```

The commits on github now trigger buildbot to verify compilation:
  https://buildfarm.opencsw.org/buildbot/waterfall?category=collectd

**Comment by xtra-be** [comment] 2015-06-09 12:51
see also issue 977

**Comment by octo** [comment] 2015-06-10 07:28
> The commits on github now trigger buildbot to verify compilation:

That is awesome! Thank you!

Regarding the bug, it appears that we're missing the definition of `struct ip6_ext`. In #348, a furhter duplicate of this bug, @ymettier notes that:

> I noticed in /usr/include/netinet/ip_compat.h that `ip6_ext` will compile if the macro `SOLARIS2` is defined (and on Solaris 11, should be defined to 11).

**Comment by octo** [comment] 2015-06-10 07:45
Closing this in favour of #348.

**Closed by octo** 2015-06-10 07:45 UTC
Labels: Bug, solaris only
