### ISSUE TITLE
collectd ethstat reporting constantly "No stats available" (on vlans)

### ISSUE THREAD

**Issue by f1-outsourcing** [collectd/collectd#2661] opened 2018-01-21 21:29 UTC
collectd-disk-5.8.0-2.el7.x86_64
collectd-ceph-5.8.0-2.el7.x86_64
collectd-ipmi-5.8.0-2.el7.x86_64
collectd-5.8.0-2.el7.x86_64

CentOS Linux release 7.4.1708 (Core)

## Expected behavior
Nothing to report

## Actual behavior

```
an 21 22:24:47 c04 collectd[15083]: ethstat plugin: No stats available for eth4.601
Jan 21 22:24:47 c04 collectd[15083]: ethstat plugin: No stats available for eth4.601
Jan 21 22:24:49 c02 collectd[31508]: ethstat plugin: No stats available for eth4.529
Jan 21 22:24:49 c02 collectd[31508]: ethstat plugin: No stats available for eth4.529
Jan 21 22:24:49 c02 collectd[31508]: ethstat plugin: No stats available for eth4.601
Jan 21 22:24:49 c02 collectd[31508]: ethstat plugin: No stats available for eth4.601
Jan 21 22:24:55 c01 collectd[26331]: ethstat plugin: No stats available for eth4.529
Jan 21 22:24:55 c01 collectd[26331]: ethstat plugin: No stats available for eth4.529
Jan 21 22:24:55 c01 collectd[26331]: ethstat plugin: No stats available for eth4.601
Jan 21 22:24:55 c01 collectd[26331]: ethstat plugin: No stats available for eth4.601
Jan 21 22:24:57 c04 collectd[15083]: ethstat plugin: No stats available for eth4.529
Jan 21 22:24:57 c04 collectd[15083]: ethstat plugin: No stats available for eth4.529
Jan 21 22:24:57 c04 collectd[15083]: ethstat plugin: No stats available for eth4.601
Jan 21 22:24:57 c04 collectd[15083]: ethstat plugin: No stats available for eth4.601
Jan 21 22:24:59 c02 collectd[31508]: ethstat plugin: No stats available for eth4.529
Jan 21 22:24:59 c02 collectd[31508]: ethstat plugin: No stats available for eth4.529
Jan 21 22:24:59 c02 collectd[31508]: ethstat plugin: No stats available for eth4.601
Jan 21 22:24:59 c02 collectd[31508]: ethstat plugin: No stats available for eth4.601
Jan 21 22:25:05 c01 collectd[26331]: ethstat plugin: No stats available for eth4.529
Jan 21 22:25:05 c01 collectd[26331]: ethstat plugin: No stats available for eth4.529
Jan 21 22:25:05 c01 collectd[26331]: ethstat plugin: No stats available for eth4.601
Jan 21 22:25:05 c01 collectd[26331]: ethstat plugin: No stats available for eth4.601
Jan 21 22:25:07 c04 collectd[15083]: ethstat plugin: No stats available for eth4.529
Jan 21 22:25:07 c04 collectd[15083]: ethstat plugin: No stats available for eth4.529
Jan 21 22:25:07 c04 collectd[15083]: ethstat plugin: No stats available for eth4.601
Jan 21 22:25:07 c04 collectd[15083]: ethstat plugin: No stats available for eth4.601
Jan 21 22:25:09 c02 collectd[31508]: ethstat plugin: No stats available for eth4.529
Jan 21 22:25:09 c02 collectd[31508]: ethstat plugin: No stats available for eth4.529
```

## Steps to reproduce

```
[@c01 ~]# cat /etc/collectd.d/11-network.conf
<LoadPlugin ethstat>
  Globals true
</LoadPlugin>

<Plugin ethstat>
        # selecting specific interfaces does not seem to work
        Interface "eth4.529"
        Interface "eth4.601"
        Interface "tun1"
#       Map "rx_csum_offload_errors" "if_rx_errors" "checksum_offload"
#       Map "multicast" "if_multicast"
#       MappedOnly true
</Plugin>
```

**Comment by rpv-tomsk** [comment] 2018-01-23 11:22
Hi!

I don't understand, what is the problem you try to solve?
If no stats should be reported, then user has to remove the interface from configuration. 
No errors will be in logs then. 

I think we shouldn't remove 'No stats available' message from plugin code.
Is I'm missing something?

**Comment by f1-outsourcing** [comment] 2018-01-23 20:48
Is this plugin doing only doing physical interfaces? No vlan's, bonds etc? Why do I have then data in influxdb of them?
The above interfaces eth4.529, eth4.601 and tun1 are present and up. So why do I get a message no stats available?

**Comment by rpv-tomsk** [comment] 2018-01-24 07:43
> the problem that needs to solved is that there should not be any logging if ethernet interfaces are polled (and thus data is collected and submitted).

If you try to look into plugin code, you could see what no data can be collected when this error is logged:

```
  n_stats = (size_t)drvinfo.n_stats;
  if (n_stats < 1) {
    close(fd);
    ERROR("ethstat plugin: No stats available for %s", device);
    return -1;
  }
```
So, the cause of error is misconfiguration.

**Comment by rpv-tomsk** [comment] 2018-01-24 07:50
> if I have such an configuration file, I don't have any notifications, which is fine. Except for all the extra 'garbage' being collected on macvtapsXX, greX, lo and eth's I am not using.

Looking into plugin code, I can say what without explicit configuration plugin does nothing. 
No interfaces is polled, no metrics is reported and no messages in logs.

**Comment by f1-outsourcing** [comment] 2018-01-24 09:47
You are right there is a plugin interface in the main config that is doing this. Actually this is the one I was looking for, it has also the option IgnoreSelected false.

**Comment by rpv-tomsk** [comment] 2018-01-24 10:04
Ok, let's close this then.
Feel free to create a new one if needed ;-)

**Closed by rpv-tomsk** 2018-01-24 10:04 UTC
Labels: Pending contributor action
