### ISSUE TITLE
IPMI SuperMicro PowerSupply

### ISSUE THREAD

**Issue by DawgTool** [collectd/collectd#920] opened 2015-01-29 19:19 UTC
Would like to monitor the power supplies.  It appears that I have status (on/off) available.

Please let me know if you need any additional information.

collectd: ipmi plugin: sensor_list_add: Ignore sensor PS2 Status power_supply (10.2), because I don't know how to handle its type (0x8, power_supply). If you need this sensor, please file a bug report.
collectd: ipmi plugin: sensor_list_add: Ignore sensor  management controller firmware (46.4), because I don't know how to handle its type (0xdc, invalid). If you need this sensor, please file a bug report.
collectd: ipmi plugin: sensor_list_add: Ignore sensor  management controller firmware (46.3), because I don't know how to handle its type (0xdc, invalid). If you need this sensor, please file a bug report.
collectd: ipmi plugin: sensor_list_add: Ignore sensor  management controller firmware (46.2), because I don't know how to handle its type (0xdc, invalid). If you need this sensor, please file a bug report.
collectd: ipmi plugin: sensor_list_add: Ignore sensor  management controller firmware (46.1), because I don't know how to handle its type (0xdc, invalid). If you need this sensor, please file a bug report.
collectd: ipmi plugin: sensor_list_add: Ignore sensor PS1 Status power_supply (10.1), because I don't know how to handle its type (0x8, power_supply). If you need this sensor, please file a bug report.

Device ID                 : 32
Device Revision           : 1
Firmware Revision         : 1.78
IPMI Version              : 2.0
Manufacturer ID           : 10876
Manufacturer Name         : Supermicro
Product ID                : 1802 (0x070a)
Product Name              : Unknown (0x70A)
Device Available          : yes
Provides Device SDRs      : no
Additional Device Support :
    Sensor Device
    SDR Repository Device
    SEL Device
    FRU Inventory Device
    IPMB Event Receiver
    IPMB Event Generator
    Chassis Device

CPU1 Temp        | 45.000     | degrees C  | ok    | 0.000     | 0.000     | 0.000     | 85.000    | 88.000    | 90.000
CPU2 Temp        | 43.000     | degrees C  | ok    | 0.000     | 0.000     | 0.000     | 85.000    | 88.000    | 90.000
System Temp      | 32.000     | degrees C  | ok    | -9.000    | -7.000    | -5.000    | 80.000    | 85.000    | 90.000
Peripheral Temp  | 55.000     | degrees C  | ok    | -9.000    | -7.000    | -5.000    | 80.000    | 85.000    | 90.000
PCH Temp         | 57.000     | degrees C  | ok    | -11.000   | -8.000    | -5.000    | 90.000    | 95.000    | 100.000
P1-DIMMA1 TEMP   | 34.000     | degrees C  | ok    | 1.000     | 2.000     | 4.000     | 80.000    | 85.000    | 90.000
P1-DIMMA2 TEMP   | na         |            | na    | na        | na        | na        | na        | na        | na
P1-DIMMB1 TEMP   | 33.000     | degrees C  | ok    | 1.000     | 2.000     | 4.000     | 80.000    | 85.000    | 90.000
P1-DIMMB2 TEMP   | na         |            | na    | na        | na        | na        | na        | na        | na
P1-DIMMC1 TEMP   | 37.000     | degrees C  | ok    | 1.000     | 2.000     | 4.000     | 80.000    | 85.000    | 90.000
P1-DIMMC2 TEMP   | na         |            | na    | na        | na        | na        | na        | na        | na
P1-DIMMD1 TEMP   | 36.000     | degrees C  | ok    | 1.000     | 2.000     | 4.000     | 80.000    | 85.000    | 90.000
P1-DIMMD2 TEMP   | na         |            | na    | na        | na        | na        | na        | na        | na
P2-DIMME1 TEMP   | 33.000     | degrees C  | ok    | 1.000     | 2.000     | 4.000     | 80.000    | 85.000    | 90.000
P2-DIMME2 TEMP   | na         |            | na    | na        | na        | na        | na        | na        | na
P2-DIMMF1 TEMP   | 32.000     | degrees C  | ok    | 1.000     | 2.000     | 4.000     | 80.000    | 85.000    | 90.000
P2-DIMMF2 TEMP   | na         |            | na    | na        | na        | na        | na        | na        | na
P2-DIMMG1 TEMP   | 32.000     | degrees C  | ok    | 1.000     | 2.000     | 4.000     | 80.000    | 85.000    | 90.000
P2-DIMMG2 TEMP   | na         |            | na    | na        | na        | na        | na        | na        | na
P2-DIMMH1 TEMP   | 33.000     | degrees C  | ok    | 1.000     | 2.000     | 4.000     | 80.000    | 85.000    | 90.000
P2-DIMMH2 TEMP   | na         |            | na    | na        | na        | na        | na        | na        | na
FAN1             | 4350.000   | RPM        | ok    | 300.000   | 450.000   | 600.000   | 18975.000 | 19050.000 | 19125.000
FAN2             | na         |            | na    | na        | na        | na        | na        | na        | na
FAN3             | 4500.000   | RPM        | ok    | 300.000   | 450.000   | 600.000   | 18975.000 | 19050.000 | 19125.000
FANA             | na         |            | na    | na        | na        | na        | na        | na        | na
VTT              | 1.040      | Volts      | ok    | 0.816     | 0.864     | 0.912     | 1.344     | 1.392     | 1.440
CPU1 Vcore       | 0.720      | Volts      | ok    | 0.480     | 0.512     | 0.544     | 1.488     | 1.520     | 1.552
CPU2 Vcore       | 0.768      | Volts      | ok    | 0.480     | 0.512     | 0.544     | 1.488     | 1.520     | 1.552
VDIMM AB         | 1.344      | Volts      | ok    | 1.104     | 1.152     | 1.200     | 1.648     | 1.696     | 1.744
VDIMM CD         | 1.344      | Volts      | ok    | 1.104     | 1.152     | 1.200     | 1.648     | 1.696     | 1.744
VDIMM EF         | 1.344      | Volts      | ok    | 1.104     | 1.152     | 1.200     | 1.648     | 1.696     | 1.744
VDIMM GH         | 1.344      | Volts      | ok    | 1.104     | 1.152     | 1.200     | 1.648     | 1.696     | 1.744
3.3V             | 3.264      | Volts      | ok    | 2.640     | 2.784     | 2.928     | 3.648     | 3.792     | 3.936
+3.3VSB          | 3.312      | Volts      | ok    | 2.640     | 2.784     | 2.928     | 3.648     | 3.792     | 3.936
5V               | 5.056      | Volts      | ok    | 4.096     | 4.288     | 4.480     | 5.504     | 5.696     | 6.912
+5VSB            | 5.056      | Volts      | ok    | 4.096     | 4.288     | 4.480     | 5.504     | 5.696     | 6.912
12V              | 11.978     | Volts      | ok    | 10.176    | 10.494    | 10.812    | 13.250    | 13.568    | 13.886
VBAT             | 3.168      | Volts      | ok    | 2.400     | 2.544     | 2.688     | 3.552     | 3.696     | 3.840
PS1 Status       | 0x1        | discrete   | 0x0100| na        | na        | na        | na        | na        | na
PS2 Status       | 0x1        | discrete   | 0x0100| na        | na        | na        | na        | na        | na

**Comment by BartVB** [comment] 2015-03-02 08:53
This seems to be a dupe of #735.

**Comment by rubenk** [comment] 2016-02-26 16:17
Indeed, it is. Closing this.

**Closed by rubenk** 2016-02-26 16:17 UTC
