### ISSUE TITLE
DPDK plugin with collectd fails to compile with fedora 25

### ISSUE THREAD

**Issue by prateek1192** [collectd/collectd#2142] opened 2017-01-19 08:05 UTC
*   Version of collectd: collectd-5.7.0
*   Operating system / distribution: Fedora 25

## Expected behavior

I expected the plugin to compile

## Actual behavior

The plugin fails to compile with the error 

In file included from ./daemon/common.h:33:0,
                 from dpdkstat.c:33:
dpdkstat.c: In function 'dpdk_config_init_default':
dpdkstat.c:162:13: error: format '%lu' expects argument of type 'long unsigned int', but argument 3 has type 'uint64_t {aka long long unsigned int}' [-Werror=format=]
     WARNING("dpdkstat: No time interval was configured, default value %lu ms "
             ^
./daemon/plugin.h:398:46: note: in definition of macro 'WARNING'
 #define WARNING(...) plugin_log(LOG_WARNING, __VA_ARGS__)

I have tried adding a mssse3 flag to it even though it has gcc > 4.9. The result is the same

[root@         ]# gcc --version
gcc (GCC) 6.3.1 20161221 (Red Hat 6.3.1-1)
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

## Steps to reproduce

*   Try to enable plugin in the spec file being used for integrating collectd with dpdk
*   You can get the error

**Comment by rubenk** [comment] 2017-01-19 09:56
Which version of dpdk?

**Comment by prateek1192** [comment] 2017-01-19 14:56
the version of dppk is 16.4. If you want the specific output of a command to confirm that, please let me know the command .

**Comment by rubenk** [comment] 2017-01-19 15:00
I take it you mean 16.04? That should work fine, I think the build warning is harmless but collectd builds with -Werror by default. You can override it with --disable-werror.

This looks to be fixed in master, could you check that?

**Comment by prateek1192** [comment] 2017-01-19 15:05
Can you please point me towards the patch which fixes it ?

**Comment by rubenk** [comment] 2017-01-19 15:29
Probably https://github.com/collectd/collectd/commit/1e8a95944f39cf4d552f2afed8e26b93febd50ec

**Comment by prateek1192** [comment] 2017-01-20 07:38
Thanks rubenk. I understand that the version of collectd 5.7 might not have the above patch and I should take in the master branch and package it and then try using it. It would be great if you could point me to how to do that. Or should i wait for the official package to come in and then only use it. I tried looking in the collectd-5.7.0 and it does not have the above mentioned patch. Your replies are highly appreciated.

**Comment by rubenk** [comment] 2017-01-20 11:52
Like I said earlier, it's just a build warning, just compile with --disable-werror.

**Comment by rubenk** [comment] 2017-01-20 12:22
Just a thought, what architecture are you compiling on, 64 bit or 32 bit?

**Comment by prateek1192** [comment] 2017-01-24 05:31
rubenk, just figured out that i was compiling on a 32 bit machine and i guess that was the reason for the above error. I have switched to a 64 bit machine and a 64 bit OS and have checked that my physical host supports 64 bit.

The old error is gone but i have got a new error now 

make[3]: *** [dpdkstat_la-dpdkstat.lo] Error 1

Also i have this error 

dpdkstat.c: In function 'dpdk_helper_run':
dpdkstat.c:502:10: error: implicit declaration of function 'rte_eal_primary_proc_alive' [-Werror=implicit-function-declaration]
     if (!rte_eal_primary_proc_alive(g_configuration->file_prefix)) {

This one should not be a problem, but the 1st one should be. I am trying to pass a Wnoerror flag while building to see if the first one is a problem.

**Comment by prateek1192** [comment] 2017-01-24 05:41
The Wnoerror flag helped to an extent but the build displayed a message in the end " File not found: /root/rpmbuild/BUILDROOT/collectd-5.7.0-2.fc24.x86_64/usr/lib64/collectd/dpdk.so". So the build is still not succeeding. I have a dell power blade with an intel processor on which i am building, also one of my collegue was able to get a build using the same spec file on a VM, is there something hardware specific collectd requires to build ?

**Comment by rubenk** [comment] 2017-01-24 09:11
There's nothing hardware specific.

Please show the complete build output and config.log. Without them there's no telling what the issue is.

**Comment by prateek1192** [comment] 2017-01-24 09:51
PFA. Please let me know if you need something else.


[build_logs.txt](https://github.com/collectd/collectd/files/726228/build_logs.txt)

[config.txt](https://github.com/collectd/collectd/files/726237/config.txt)

**Comment by rubenk** [comment] 2017-01-24 13:44
Thanks. Unfortunately I cannot reproduce this on Fedora 25.
`rte_eal_primary_proc_alive` is decleared in /usr/include/dpdk/rte_eal.h on my system, and that header is included by src/dpdkstat.c

 Where did you get dpdk from?

**Comment by prateek1192** [comment] 2017-01-24 14:01
I simply have the statement 

%if 0%{?enable_dpdk} == 1
%package dpdk
Summary:       DPDK plugin for collectd
Requires:      %{name}%{?_isa} = %{version}-%{release}
BuildRequires: dpdk-devel
%description  dpdk
This plugin collects data from dpdk
%endif

in my spec file. So it should take the latest version of dpdk-devel on fedora and build dpdk. 

Also the version of dpdk-devel is 2.2.0-5 as confirmed using this command

[root@dell-fc430-5 collectd]# yum install dpdk-devel
Redirecting to '/usr/bin/dnf install dpdk-devel' (see 'man yum2dnf')

Last metadata expiration check: 1:15:05 ago on Tue Jan 24 18:15:24 2017.
Package dpdk-devel-2.2.0-5.fc24.x86_64 is already installed, skipping.

**Comment by maryamtahhan** [comment] 2017-01-24 14:05
Hi
I think the DPDK version is the issue… the min version of DPDK to use is 16.04
https://github.com/collectd/collectd/blob/master/docs/BUILD.dpdkstat.md

The dpdkstat plugin has the following requirements:

  *   DPDK 16.04 or later
  *   GCC 4.9 or later

DPDK 2.2 doesn’t have the functions required to do monitoring of the primary process.

BR
Maryam

**Comment by rubenk** [comment] 2017-01-24 14:21
Yes, 16.04 is the minimum version, that's why it was the first thing I asked in https://github.com/collectd/collectd/issues/2142#issuecomment-273797174, and @prateek1192 said he was using 16.04, on Fedora 25.

**Closed by rubenk** 2017-01-24 14:21 UTC
Labels: Pending feedback
