### ISSUE TITLE
.rrd: illegal attempt to update using time ... (minimum one second step)

### ISSUE THREAD

**Issue by RobertMortimer** [collectd/collectd#781] opened 2014-10-27 12:31 UTC
We have our dbi plugin set to do database checks every 60 seconds. Collected still runs on it's 10 sec cycle. As a result only 1 in 6 of collected processing cycle receives an update for these metrics. The other 5 out of six the rrd update fails as it tries to log the stale value that has not been updated by dbi - this causes a duplicate value error and is logged to the error. Disabling the rrd plugin stops the dbi plugin from working. How do we bring the rrd update cycles in line with the dbi cycles?

Collectd version 5.4.1 (RPM built from source)
OS = RHEL 6.6

**Comment by rubenk** [comment] 2016-08-06 07:56
Hi @RobertMortimer!

Can you show us your collectd.conf?
One issue I can think of is that you changed the Interval for the dbi plugin, but the interval in the existing rrd files is still set to 10 seconds. You can check this with 'rrdtool info'. Look for the 'step' line.

**Comment by octo** [comment] 2016-08-06 12:35
When the RRD file is created, the interval is also stored in the file. If you change the interval in collectd at a later time, you have to delete the RRD file and have it automatically created again. As a work-around, if you don't want to loose existing data, you can tune the heartbeat of the existing RRD files to something like 120 seconds, which should fix the issue too.

Closing as *working as intended*

**Closed by octo** 2016-08-06 12:35 UTC
Labels: Waiting
