### ISSUE TITLE
Some plugins are undocumented in collectd.conf(5)

### ISSUE THREAD

**Issue by edigaryev** [collectd/collectd#1937] opened 2016-09-16 13:27 UTC
Examples:

* users
* entropy

There's probably more to it than that.

**Comment by octo** [comment] 2016-09-16 18:47
These two plugins don't have an entry in *collectd.conf(5)* because they don't offer any config options. Do you have any suggestions where these plugins should be documented instead?

**Comment by edigaryev** [comment] 2016-09-17 07:17
>These two plugins don't have an entry in collectd.conf(5) because they don't offer any config options.

Right, but they still go into collectd.conf anyway.

>Do you have any suggestions where these plugins should be documented instead?

How about a different section of collectd.conf(5)?

* GLOBAL OPTIONS
* PLUGINS WITHOUT OPTIONS
* PLUGINS WITH OPTIONS
* THRESHOLD CONFIGURATION
* etc.

**Comment by rubenk** [comment] 2016-09-19 08:57
Dupe of #1682

**Closed by rubenk** 2016-09-19 08:57 UTC
Labels: documentation, Pending feedback
