### ISSUE TITLE
Unable to compile python plugin with python-3.3

### ISSUE THREAD

**Issue by trtrmitya** [collectd/collectd#505] opened 2014-01-03 08:41 UTC
Hello!

I try to compile collected-5.4.0 on FreeBSD with python support. I want to use python version 3
(3.3.3 to be specific).

manpage for collectd-python mentions python version 3, so I assume it is supported.

But I get the following error:

libtool: compile:  cc -DHAVE_CONFIG_H -I. -DPREFIX=\"/usr/local\" -DCONFIGFILE=\
"/usr/local/etc/collectd.conf\" -DLOCALSTATEDIR=\"/var\" -DPKGLOCALSTATEDIR=\"/v
ar/db/collectd\" -DPIDFILE=\"/var/run/collectd.pid\" -DPLUGINDIR=\"/usr/local/li
b/collectd\" -DPKGDATADIR=\"/usr/local/share/collectd\" -I/usr/local/include/pyt
hon3.3m -I/usr/local/include -Wall -Werror -fno-strict-aliasing -Wno-strict-alia
sing -O2 -pipe -O2 -fno-strict-aliasing -pipe -MT python_la-python.lo -MD -MP -MF .deps/python_la-python.Tpo -c python.c  -fPIC -DPIC -o .libs/python_la-python.
o
cc1: warnings being treated as errors
python.c: In function 'cpy_init_python':
python.c:1023: warning: passing argument 2 of 'PySys_SetArgv' from incompatible pointer type
python.c: In function 'cpy_config':
python.c:1071: warning: implicit declaration of function 'PyUnicode_SetDefaultEncoding'
gmake[3]: *** [python_la-python.lo] Error 1
gmake[3]: Leaving directory `/place/WRK/ports/net-mgmt/collectd5/work/collectd-5.4.0/src'
gmake[2]: *** [all-recursive] Error 1

**Comment by trtrmitya** [comment] 2015-01-09 10:38
Hello!

Any chance python3 support could be fixed please?

**Comment by trtrmitya** [comment] 2015-01-12 19:09
Time comes, I tried with python3.4 and it compiles!  But dumps core on start:
# collectd -f
Fatal Python error: no mem for sys.argv
ValueError: character U+6f633c00 is not in range [U+0000; U+10ffff]
Abort (core dumped)

**Comment by rubenk** [comment] 2016-08-05 12:05
Fixed by 	920d5ea

@trtrmitya I just compiled collectd with python33, python34 and python35 on FreeBSD current but can't reproduce your coredump. If you can still trigger it with the latest version of collectd from git, please open a new issue, preferable with a stack trace.

**Closed by rubenk** 2016-08-05 12:05 UTC
Labels: Bug, feature request
