### ISSUE TITLE
ipmi plugin: SDR fetch error getting sdr 0x0: c1

### ISSUE THREAD

**Issue by Wolzy** [collectd/collectd#2710] opened 2018-03-08 13:01 UTC
**First apologize for my poor English.** 

*   Version of collectd: 5.8.0(clone from branch "master")
*   Operating system / distribution: Red Hat Enterprise Linux Server release 7.1 (Maipo)

## Expected behavior

Collect BMC sensor data from x86 servers, including HP, Huawei, Dell, etc.

## Actual behavior

I collected data from other servers, such as HP, Huawei, no problem, but collected from the DELL server, collectd error log is as follows::

> [2018-03-08 17:17:09] ipmi plugin: 132.78.253.70(0.20)(s,0) sdr.c(handle_sdr_data): SDR fetch error getting sdr 0x0: c1
[2018-03-08 17:17:09] ipmi plugin: 132.78.253.70(5.20)(s,0) sdr.c(handle_sdr_data): SDR fetch error getting sdr 0x0: c1
[2018-03-08 17:17:10] ipmi plugin: 132.78.253.70 .1.20.2.0.0.0 normal_fru.c(process_fru_info): FRU fields did not occur in the correct order
[2018-03-08 17:17:10] ipmi plugin: 132.78.253.70 .1.20.2.0.0.0 fru.c(fetch_complete): Unable to decode FRU information
[2018-03-08 17:17:10] ipmi plugin: 132.78.253.70 .1.20.1.0.0.0 normal_fru.c(process_fru_info): FRU fields did not occur in the correct order
[2018-03-08 17:17:10] ipmi plugin: 132.78.253.70 .1.20.1.0.0.0 fru.c(fetch_complete): Unable to decode FRU information
[2018-03-08 17:17:10] ipmi plugin: 132.78.253.70 .1.20.14.0.3.0 normal_fru.c(process_fru_info): FRU fields did not occur in the correct order
[2018-03-08 17:17:10] ipmi plugin: 132.78.253.70 .1.20.14.0.3.0 fru.c(fetch_complete): Unable to decode FRU information
[2018-03-08 17:17:10] ipmi plugin: 132.78.253.70 .1.20.13.0.2.0 normal_fru.c(process_fru_info): FRU fields did not occur in the correct order
[2018-03-08 17:17:10] ipmi plugin: 132.78.253.70 .1.20.13.0.2.0 fru.c(fetch_complete): Unable to decode FRU information
[2018-03-08 17:17:10] ipmi plugin: 132.78.253.70 .1.20.12.0.1.0 normal_fru.c(process_fru_info): FRU fields did not occur in the correct order
[2018-03-08 17:17:10] ipmi plugin: 132.78.253.70 .1.20.12.0.1.0 fru.c(fetch_complete): Unable to decode FRU information
[2018-03-08 17:17:10] ipmi plugin: 132.78.253.70 .1.20.10.0.3.0 normal_fru.c(process_fru_info): FRU fields did not occur in the correct order
[2018-03-08 17:17:10] ipmi plugin: 132.78.253.70 .1.20.10.0.3.0 fru.c(fetch_complete): Unable to decode FRU information
[2018-03-08 17:17:13] ipmi plugin: 132.78.253.70 .1.20.4.0.3.0 normal_fru.c(process_fru_info): FRU fields did not occur in the correct order
[2018-03-08 17:17:13] ipmi plugin: 132.78.253.70 .1.20.4.0.3.0 fru.c(fetch_complete): Unable to decode FRU information

## Steps to reproduce

*   Get the latest version from github
*   Recompile and install
*   and my ipmi plugin configration:

> <Instance "Dell R730">
    Host "Dell R730-1"
    Address "132.78.253.70"
    Username "username"
    Password "passowrd"
    Sensor "temperature"
    Sensor "voltage"
    Sensor "current"
    IgnoreSelected false
    NotifySensorAdd false
    NotifySensorRemove true
    NotifySensorNotPresent false
  </Instance>

**Comment by rpv-tomsk** [comment] 2018-03-08 16:58
Hi!

Which version of OpenIPMI you have? Please use recent version, at least 2.0.22 or later. 
Maybe that can help you to solve your issue.

**Comment by Wolzy** [comment] 2018-03-08 23:48
I have tried OpenIPMI 2.0.19 and 2.0.24 versions, all have this problem.

**Comment by rpv-tomsk** [comment] 2018-03-09 05:08
All the messages you shown are messages from OpenIPMI library, reported by Collectd which uses it inside.

Your problem is quite old, as shown by internet search by phrase "dell FRU fields did not occur in the correct order". Such a search has many results found. And, I think, this issue still not resolved. 
Please look, for example, this link: https://sourceforge.net/p/openipmi/mailman/message/18801866/

You may refer to OpenIPMI project with this issue...
I see almost no way how to fix this in Collectd code. 

Only one idea exists: disable `IPMI_OPEN_OPTION_FRUS` option of `ipmi_open_domain()` call.

If you can patch and compile, you can try the following:

```
diff --git a/src/ipmi.c b/src/ipmi.c
index 2db344e..32e9ee7 100644
--- a/src/ipmi.c
+++ b/src/ipmi.c
@@ -937,7 +937,12 @@ static int c_ipmi_thread_init(c_ipmi_instance_t *st) {
   }

   ipmi_open_option_t opts[] = {
-      {.option = IPMI_OPEN_OPTION_ALL, {.ival = 1}},
+      {.option = IPMI_OPEN_OPTION_ALL, {.ival = 0}},
+      {.option = IPMI_OPEN_OPTION_SDRS, {.ival = 1}},
+      {.option = IPMI_OPEN_OPTION_FRUS, {.ival = 0}},
+      {.option = IPMI_OPEN_OPTION_SEL, {.ival = 0}},
+      {.option = IPMI_OPEN_OPTION_IPMB_SCAN, {.ival = 1}},
+      {.option = IPMI_OPEN_OPTION_OEM_INIT, {.ival = 1}},
 #ifdef IPMI_OPEN_OPTION_USE_CACHE
       /* OpenIPMI-2.0.17 and later: Disable SDR cache in local file */
       {.option = IPMI_OPEN_OPTION_USE_CACHE, {.ival = 0}},
```

Explanation:

In `OpenIPMI-2.0.xxx/lib/domain.c`,  there is `process_options()` function. I lists supported options.

You should disable `IPMI_OPEN_OPTION_ALL`  in Collectd code (set it to zero, not just remove), and enable all needed options, such as `IPMI_OPEN_OPTION_SDRS`, `IPMI_OPEN_OPTION_SEL` and possible others.

Hope that can help.

**Comment by Wolzy** [comment] 2018-03-09 06:32
In accordance with what you said, I patched and recompile ipmi.c, but the results did not change, because I found what I need exactly is sdr-related, so I must set IPMI_OPEN_OPTION_SDRS to 1, otherwise it will not achieve results.
I will also issue an issue to the OpenIPMI project later to see if there is a solution.
Also ask, if I want to get only temperature and power through configuration, is there any way to get around this problem?

**Comment by rpv-tomsk** [comment] 2018-03-09 09:37
>so I must set IPMI_OPEN_OPTION_SDRS to 1

Yes, that was a typo which was fixed in comment, but not in email notification. Sorry =)

>If I want to get only temperature and power through configuration, is there any way to get around this problem?

Sorry, I have no direct answer. You can try to set required sensors with use of `Sensor` option.

>When I was testing with ipmitool, 
Just want to clarify what `ipmitool` does not use `OpenIPMI` library inside.

Collectd code uses OpenIPMI library, and code is built on callbacks. 
Reported error occurs inside of OpenIPMI logic and Collectd code can't influent if OpenIPMI will call `entity` or `sensor` update handler or not.

**Comment by Wolzy** [comment] 2018-03-09 10:52
In the process of my experiment, I modified the configuration of the plugin and found that suddenly I could collect the data. Although I don't know which of the changes were in effect, I think I can send it for peoples reference ^ _ ^
My steps are as follows:
* First modify the ipmi.c and just enabled IPMI_OPEN_OPTION_SDRS, according to the suggestion given by rpv-tomsk.
* Modified the configuration file, one of instances as follows:
> <Instance "10.4.20.1">
Host "10.4.20.1"
Address "10.4.20.1"
Username "username"
Password "passowrd"
Sensor "temperature"
Sensor "current"
Sensor "fanspeed"
IgnoreSelected true
SELEnabled False
</Instance>

Later, I will change my parameters and do more tests. If possible, I will update this comment.
In the end, thank you very much, rpv-tomsk.

**Comment by rpv-tomsk** [comment] 2018-03-09 13:14
>Sensor "temperature"
>Sensor "current"
>Sensor "fanspeed"
>IgnoreSelected true

Is that is really what you use/need???

Can you please reproduce all the steps, starting from unpatched version and full sensors set (with no `Sensor` option  configured) ? 

So, the steps to check (until first success):

1) Unpatched, all sensors enabled;
2) Unpatched, reduced set of sensors;
3) Patched, all sensors enabled;
4) Patched, reduced set of sensors;

Thanks!

**Comment by Wolzy** [comment] 2018-03-09 16:00
I had obtained the original version from github, and then I did some tests first. The results are as follows:
## 1.Unpatched, all sensors enabled;
Plug-in configuration is as follows:
> Sensor "Inlet Temp system_board (7.1)"
     Sensor "Current system_board (7.1)"
     Sensor "Pwr Consumption system_board (7.1)"
     Sensor "Temp processor (3.1)"
     Sensor "Temp processor (3.2)"
     Sensor "Temp processor (3.3)"
     Sensor "Temp processor (3.4)"
     IgnoreSelected false
**With this configuration, the program will report an error and exit illegally.**

## 2.Unpatched, reduced set of sensors:
### 2.1.Change "IgnoreSelected" to "True":
**the program report and error and exit illegally.**
### 2.2.remove the "IgnoreSelected":
there is a prompt "sdr.c(handle_sdr_data): SDR fetch error getting sdr 0x0: c1", but:
1) Only one instance, except for the first execution error and exit, other attempts can be collected;
2) Add the second instance, Ibid;
3) Add the third and fourth instances, collect normally.
### 2.3.remove one or more sensors:
Same as 2.2
### 2.4.remove all sensors:
**the program report and error and exit illegally, same as 2.1**
### 2.5.add some non-existing sensors
**the program report and error and exit illegally, same as 2.1**

It‘s midnight now,  I will gradually add the following tests after dawn. ^_^

**Comment by rpv-tomsk** [comment] 2018-03-10 19:28
>1.Unpatched, all sensors enabled;

Configuration you show in this block selects exact lists of sensors.
That does not match to "all sensors enabled".

Something is wrong here.

----

>With this configuration, the program will report an error and exit illegally.

Can you please clarify what exact message you see in this case?
As I understand, that message is something was not posted in this topic yet.

----

As I understand, provided patch does not changes this case much.
Main reason of the issue is some 'broken' sensor which can't be handled by OpenIPMI.
That confirmed by success in 2.2 and 2.3. Point me if my understanding is wrong.

**Comment by Wolzy** [comment] 2018-03-11 08:51
Sorry, I can't test it on the weekend. I'll add a test tomorrow and I will report the result

**Comment by rpv-tomsk** [comment] 2018-03-29 03:47
Closed due to no response. Feel free to reopen if that is needed.

**Closed by rpv-tomsk** 2018-03-29 03:47 UTC
