### ISSUE TITLE
Implausible Ping readings

### ISSUE THREAD

**Issue by FloRinke** [collectd/collectd#2861] opened 2018-07-15 14:37 UTC
*   Version of collectd: 5.7.1, installed from debian stretch main repo
*   Operating system / distribution: Debian stretch

## Expected behavior
Ping module should log actual ping values, those should (within margins of error) be consistent with pinging the same destination "by hand"

## Actual behavior
Ping values are completely implausible, by an order of 2 to 4 magnitudes too high. Values around 30s shouldn't even be possible, as according to the docs pings should be counted as lost when above 1s.
![collectd-ping-grafana](https://user-images.githubusercontent.com/10011822/42734717-1e655994-8849-11e8-8f03-c176c66a44b4.png)
It's not just grafana misbehaving, it's the raw values in influxdb:
```
> select * from ping_value where "host"='testhost' and "type_instance"='100.120.48.20' and "type"='ping' and time > now() - 10m
name: ping_value
time                           host     type type_instance value
----                           ----     ---- ------------- -----
2018-07-15T13:51:23.331752015Z testhost ping 100.120.48.20 18.78553333333333
2018-07-15T13:51:53.331716999Z testhost ping 100.120.48.20 8.632800000000001
2018-07-15T13:52:23.331756626Z testhost ping 100.120.48.20 15.618799999999998
2018-07-15T13:52:53.331715913Z testhost ping 100.120.48.20 18.076633333333337
2018-07-15T13:53:23.331795252Z testhost ping 100.120.48.20 23.565133333333335
2018-07-15T13:53:53.331721893Z testhost ping 100.120.48.20 12.074766666666669
2018-07-15T13:54:23.331743954Z testhost ping 100.120.48.20 20.585333333333335
2018-07-15T13:54:53.331717257Z testhost ping 100.120.48.20 13.0479
2018-07-15T13:55:23.331784606Z testhost ping 100.120.48.20 20.092800000000004
2018-07-15T13:55:53.331722009Z testhost ping 100.120.48.20 15.803833333333332
2018-07-15T13:56:23.331798243Z testhost ping 100.120.48.20 16.571666666666665
2018-07-15T13:56:53.331720601Z testhost ping 100.120.48.20 16.005566666666663
2018-07-15T13:57:23.331755735Z testhost ping 100.120.48.20 17.0253
2018-07-15T13:57:53.33171657Z  testhost ping 100.120.48.20 19.505666666666666
2018-07-15T13:58:23.331761258Z testhost ping 100.120.48.20 12.296866666666668
2018-07-15T13:58:53.331730901Z testhost ping 100.120.48.20 12.122133333333334
2018-07-15T13:59:23.331722324Z testhost ping 100.120.48.20 21.12826666666667
2018-07-15T13:59:53.331730686Z testhost ping 100.120.48.20 24.52033333333333
2018-07-15T14:00:23.331754229Z testhost ping 100.120.48.20 16.366133333333334
2018-07-15T14:00:53.331707575Z testhost ping 100.120.48.20 15.600300000000002
> ^C
```
When pinged manually, the RTT is as low as you'd expect inside a local network.
```
root@testhost:~# ping 100.120.48.20
PING 100.120.48.20 (100.120.48.20) 56(84) bytes of data.
64 bytes from 100.120.48.20: icmp_seq=1 ttl=63 time=3.56 ms
64 bytes from 100.120.48.20: icmp_seq=2 ttl=63 time=3.82 ms
64 bytes from 100.120.48.20: icmp_seq=3 ttl=63 time=82.8 ms
64 bytes from 100.120.48.20: icmp_seq=4 ttl=63 time=5.26 ms
64 bytes from 100.120.48.20: icmp_seq=5 ttl=63 time=4.56 ms
64 bytes from 100.120.48.20: icmp_seq=6 ttl=63 time=4.40 ms
64 bytes from 100.120.48.20: icmp_seq=7 ttl=63 time=8.35 ms
64 bytes from 100.120.48.20: icmp_seq=8 ttl=63 time=5.40 ms
64 bytes from 100.120.48.20: icmp_seq=9 ttl=63 time=4.54 ms
64 bytes from 100.120.48.20: icmp_seq=10 ttl=63 time=3.99 ms
64 bytes from 100.120.48.20: icmp_seq=11 ttl=63 time=3.24 ms
^C
--- 100.120.48.20 ping statistics ---
11 packets transmitted, 11 received, 0% packet loss, time 10014ms
rtt min/avg/max/mdev = 3.247/11.815/82.803/22.486 ms
```
Other hosts have different values, not always as extreme as here, but always many times more than they should be.

I've also verified by watching tcpdump that the pings by collecd get answered in a timely manner:
```
root@testhost:~# tcpdump -n icmp and host 100.120.48.20
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on ens18, link-type EN10MB (Ethernet), capture size 262144 bytes
16:20:41.087398 IP 100.120.53.6 > 100.120.48.20: ICMP echo request, id 41449, seq 7822, length 84
16:20:41.093876 IP 100.120.48.20 > 100.120.53.6: ICMP echo reply, id 41449, seq 7822, length 84
16:20:42.087514 IP 100.120.53.6 > 100.120.48.20: ICMP echo request, id 41449, seq 7823, length 84
16:20:42.142233 IP 100.120.48.20 > 100.120.53.6: ICMP echo reply, id 41449, seq 7823, length 84
16:20:43.087631 IP 100.120.53.6 > 100.120.48.20: ICMP echo request, id 41449, seq 7824, length 84
16:20:43.093162 IP 100.120.48.20 > 100.120.53.6: ICMP echo reply, id 41449, seq 7824, length 84
^C
6 packets captured
6 packets received by filter
0 packets dropped by kernel
```

## Steps to reproduce
Excerpt from collectd config in use:
```
Interval 30
ReadThreads 20
WriteThreads 5
MaxPacketSize 1452

<LoadPlugin ping>
</LoadPlugin>
<Plugin ping>
	Host ...
	Host "100.120.48.20"
	Host ...
</Plugin>

<LoadPlugin network>
</LoadPlugin>
<Plugin network>
	MaxPacketSize 1452
	<Server "influxdbhost" "25826">
		SecurityLevel encrypt
		Username "collectd"
		Password "secret"
	</Server>
</Plugin>
```

**Comment by rpv-tomsk** [comment] 2018-07-22 07:03
Which version of `liboping` are you using? However, I see no significant changes for a last time.
Just setup latest Collectd from https://pkg.ci.collectd.org/  with `liboping0-1.10.0-2` from Debian packages, and all works fine. Values on chart match to `ping` command.

**Comment by mrunge** [comment] 2019-02-12 13:04
Thank you for your report. This is probably a duplicate of https://github.com/collectd/collectd/issues/473 , thus closing here.

**Closed by mrunge** 2019-02-12 13:04 UTC
