### ISSUE TITLE
Plugin iptables failed to handle option Chain, return code: 1

### ISSUE THREAD

**Issue by Whissi** [collectd/collectd#3235] opened 2019-07-29 19:27 UTC
*   Version of collectd: 5.9.1
*   Operating system / distribution: Gentoo
*   Kernel version (if applicable): 4.9.186

## Expected behavior

Plugin should load.

## Actual behavior

Plugin doesn't load and collectd will log the error
```
Plugin iptables failed to handle option Chain, return code: 1
```

## Steps to reproduce

*   Compile collectd with iptables plugin
*   Create a chain in iptables
*   Try to load iptables plugin like
```
<Plugin "iptables">
        Chain filter "mychain"
</Plugin>
```

**Comment by faxm0dem** [comment] 2019-07-29 22:03
also a duplicate of #3232

**Comment by faxm0dem** [comment] 2019-07-29 22:08
Please verify that https://github.com/collectd/collectd/pull/3237 fixes this

**Comment by Whissi** [comment] 2019-07-30 09:59
This seems to be working with the fix.

**Comment by mrunge** [comment] 2019-08-06 11:08
Should be fixed by https://github.com/collectd/collectd/pull/3237

**Closed by mrunge** 2019-08-06 11:08 UTC
Labels: Bug
